// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptHub2.Server.Data;

#nullable disable

namespace PromptHub2.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231211162955_NormalizeFieldInUserTable")]
    partial class NormalizeFieldInUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e99b398e-4e7e-46ba-9752-52b6bb8d1d42",
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "209ab5fe-d8b0-4903-bd40-2eb84825a9c2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1d52bbf-5066-4c65-936a-b9fdb04c490c",
                            Email = "William_Shields64@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "WILLIAM_SHIELDS64@YAHOO.COM",
                            NormalizedUserName = "WILLIAM_SHIELDS64@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELpaH7IiJju0+6ktRvJlT/eJ+Z6b5AdqzNtzXXevlwFfDMjhL8EebVkTMYt9Y0tGcw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a99f4c6-3a94-4b7c-965e-af76edda5579",
                            TwoFactorEnabled = false,
                            UserName = "William_Shields64@yahoo.com"
                        },
                        new
                        {
                            Id = "074ba6f7-9633-410f-bb53-6fd71c8eb890",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b9f4923-72e6-4ce9-abfe-62009e33bf0d",
                            Email = "Raphaelle22@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RAPHAELLE22@HOTMAIL.COM",
                            NormalizedUserName = "RAPHAELLE22@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHfpja4ahu1Tqqn3243xdCxfQilA9+O+ZdmiagtP+JNhtrdhbk475yRPic8DOBmW1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6c73aae-6b9a-4b38-b83a-9bbf2b304252",
                            TwoFactorEnabled = false,
                            UserName = "Raphaelle22@hotmail.com"
                        },
                        new
                        {
                            Id = "cb0daf3a-f3e4-42a3-b264-8e49bcebdcc4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44adb0d9-db68-482b-804d-c0cb31ae39dd",
                            Email = "Marta.Feeney3@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARTA.FEENEY3@YAHOO.COM",
                            NormalizedUserName = "MARTA.FEENEY3@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG3JpkiSZ6zs5DAPYGx9MrpIzeecXceYJ5borwVMvnkp3kp31QvAoOAh22wIrEm8Iw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e585e90-0bb8-4d9d-8a77-4e51f8641375",
                            TwoFactorEnabled = false,
                            UserName = "Marta.Feeney3@yahoo.com"
                        },
                        new
                        {
                            Id = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a09728ea-82c2-438a-80f5-6a5acb222229",
                            Email = "Humberto89@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HUMBERTO89@HOTMAIL.COM",
                            NormalizedUserName = "HUMBERTO89@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPSwKBppPND3of6V7nI4s4+CSG+xvab69Kq+s1y83eH5Ux1nRBWBGEHaZimGabelOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cba6896-f42b-4fd8-86f3-200f9e6bf278",
                            TwoFactorEnabled = false,
                            UserName = "Humberto89@hotmail.com"
                        },
                        new
                        {
                            Id = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01b9549a-56d0-44c9-8cd2-8137dc5c4cfa",
                            Email = "Summer64@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUMMER64@HOTMAIL.COM",
                            NormalizedUserName = "SUMMER64@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP4a/jfosGCOD3mAd8WmlHe5uahiXYzlwvzopKc6qzPvK/l6eaKBNykgB3VUp9wjtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d70ec354-5977-49e6-88c9-127c2c63c798",
                            TwoFactorEnabled = false,
                            UserName = "Summer64@hotmail.com"
                        },
                        new
                        {
                            Id = "e261f625-3e8a-422f-84c9-94bc09b14c04",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb412dec-18f6-4526-a32a-c0bd2141feaa",
                            Email = "Ross_Reichel62@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ROSS_REICHEL62@YAHOO.COM",
                            NormalizedUserName = "ROSS_REICHEL62@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBPk5eeysfjbLKiaCZ+R1ct0hYkTAPSP0XjJm9bgJe7/PIY2joUHKq4N9wGXa9uuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5655dd57-ec5d-4d2c-bdd0-1e4cd4598530",
                            TwoFactorEnabled = false,
                            UserName = "Ross_Reichel62@yahoo.com"
                        },
                        new
                        {
                            Id = "fed14519-0455-49ff-935e-14389498585d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32f2eedb-ae79-4188-8441-37b66d085a3d",
                            Email = "Howard_Emmerich8@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HOWARD_EMMERICH8@YAHOO.COM",
                            NormalizedUserName = "HOWARD_EMMERICH8@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHKo79FDhcpp/fv6JaLmo+Gv7dMzbO9b8vJ64yOvD8WH4XPnTJPWQcWYwimwawOOkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79b6b20d-4361-4820-bad6-33bf0650e0e0",
                            TwoFactorEnabled = false,
                            UserName = "Howard_Emmerich8@yahoo.com"
                        },
                        new
                        {
                            Id = "569ddf3b-ecd4-456b-aa9a-8f834b2ea573",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2d53ba27-4fdb-425c-a95c-450b789163ce",
                            Email = "Terrence_Green53@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "TERRENCE_GREEN53@HOTMAIL.COM",
                            NormalizedUserName = "TERRENCE_GREEN53@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELYW/NXSQ9gQ+0kZEwPpezufzdBrYli3fF0XrqdXL1KLF1d4tBwjsYW2UlNha9jUxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6eeba6b-b9fa-4319-ae15-625c9e96ebea",
                            TwoFactorEnabled = false,
                            UserName = "Terrence_Green53@hotmail.com"
                        },
                        new
                        {
                            Id = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f627c3bc-36b1-4048-bcc1-a4a435034cfa",
                            Email = "Heather42@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HEATHER42@GMAIL.COM",
                            NormalizedUserName = "HEATHER42@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIB8osyrxQg+h6G6M0TqKOHc9oT6WulXKNLOS8zq6/1Et5yjtHw2YNuG/12wH9CJvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a719b31-3c7a-4e4c-b4c1-f967fa821d33",
                            TwoFactorEnabled = false,
                            UserName = "Heather42@gmail.com"
                        },
                        new
                        {
                            Id = "edbcaed2-0e26-46a6-be4a-7c81e2ee850e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92ee2406-afc5-43d2-82c6-12e83980b234",
                            Email = "Charlene_OReilly@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHARLENE_OREILLY@HOTMAIL.COM",
                            NormalizedUserName = "CHARLENE_OREILLY@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0b2SoG7xvpFVEoZlVn+OjKuVU7kRXj0/GVDRdgZIvpEjFoatQjy8zpaPCveS+MDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ced14ff-edaa-4571-afc5-818a6de1738d",
                            TwoFactorEnabled = false,
                            UserName = "Charlene_OReilly@hotmail.com"
                        },
                        new
                        {
                            Id = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1e0b44d-fdef-4994-af9b-bcd2c2bed6b4",
                            Email = "fi.kwiatkowski@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FI.KWIATKOWSKI@GMAIL.COM",
                            NormalizedUserName = "FI.KWIATKOWSKI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJLLu6zAcsy0z0/8PBvp322mrMAuUjoKq4l2Q8FDh/tfCy51KzLyrxhy5kMWGCfyPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e80ef34a-e24a-4673-b80a-aad77dacafc3",
                            TwoFactorEnabled = false,
                            UserName = "fi.kwiatkowski@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3",
                            RoleId = "e99b398e-4e7e-46ba-9752-52b6bb8d1d42"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "a223464d-0d09-46d8-92a8-39b5d41dbf9b",
                            CreatedAt = new DateTime(2022, 7, 28, 1, 5, 5, 615, DateTimeKind.Unspecified).AddTicks(2144),
                            CreatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890",
                            Description = "Aut excepturi et autem. Eos occaecati commodi et labore maxime explicabo. Dolor ducimus ab labore consequatur.",
                            IsDeleted = false,
                            Name = "Distinctio neque qui libero. Quas delectus labore ducimus omnis reiciendis ea officiis. Quo hic autem aspernatur ut ea. Dolor mo",
                            UpdatedAt = new DateTime(2022, 7, 28, 1, 5, 5, 615, DateTimeKind.Unspecified).AddTicks(2144),
                            UpdatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890"
                        },
                        new
                        {
                            Id = "1ba33397-e4cc-48c2-9955-64c2aa4ee805",
                            CreatedAt = new DateTime(2023, 2, 9, 8, 27, 20, 959, DateTimeKind.Unspecified).AddTicks(3851),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Assumenda voluptate quis eos aspernatur dolor quisquam nihil enim. Ducimus enim a sunt harum ut. Aut cumque libero dolorem.",
                            IsDeleted = true,
                            Name = "Voluptate nulla quo dignissimos iste. Doloremque voluptatem incidunt aut asperiores. Enim et nesciunt similique deleniti et illo",
                            UpdatedAt = new DateTime(2023, 2, 9, 8, 27, 20, 959, DateTimeKind.Unspecified).AddTicks(3851),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "84048d83-2704-4194-9f57-24c716a8508f",
                            CreatedAt = new DateTime(2022, 8, 4, 9, 13, 37, 636, DateTimeKind.Unspecified).AddTicks(831),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Harum repellendus voluptate. Sunt aliquam nihil et aut nemo. Dolores numquam sunt magnam velit. Consequatur quia enim vel facere.",
                            IsDeleted = false,
                            Name = "Veniam earum quisquam soluta placeat perspiciatis voluptatem sint. Ipsam praesentium quo enim doloribus provident unde deleniti",
                            UpdatedAt = new DateTime(2022, 8, 4, 9, 13, 37, 636, DateTimeKind.Unspecified).AddTicks(831),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "d7895405-ea42-4547-823c-386844994f8a",
                            CreatedAt = new DateTime(2023, 3, 13, 22, 49, 46, 613, DateTimeKind.Unspecified).AddTicks(402),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Exercitationem aut voluptate reprehenderit qui similique saepe non. Explicabo commodi qui sint voluptas eaque cum et voluptate. Rerum voluptas consequatur qui perferendis voluptatum. Iusto id corporis quidem. Sed ad qui consequatur eaque similique iusto co",
                            IsDeleted = false,
                            Name = "Voluptatem maiores quo inventore optio libero. Voluptas dolorem totam totam doloribus harum. Aut deleniti quaerat dolores vel co",
                            UpdatedAt = new DateTime(2023, 3, 13, 22, 49, 46, 613, DateTimeKind.Unspecified).AddTicks(402),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "8d98fc40-1b5d-4e56-b1db-6a3381a284d9",
                            CreatedAt = new DateTime(2022, 9, 28, 4, 9, 49, 19, DateTimeKind.Unspecified).AddTicks(7216),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Expedita ipsam sed sed voluptas. Similique dolores tempore. Voluptas porro facilis nesciunt aut reiciendis quis laborum. Velit iusto eos quas. Aut sapiente debitis dolores hic consectetur rem iure ipsam.",
                            IsDeleted = false,
                            Name = "Numquam placeat laborum vel vel incidunt. Quaerat omnis laborum minus. Minus voluptatem optio. Libero corporis ducimus exercitat",
                            UpdatedAt = new DateTime(2022, 9, 28, 4, 9, 49, 19, DateTimeKind.Unspecified).AddTicks(7216),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "1cb87bd7-86c6-4d95-a152-9a54e91ed684",
                            CreatedAt = new DateTime(2022, 8, 10, 21, 52, 31, 648, DateTimeKind.Unspecified).AddTicks(5825),
                            CreatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04",
                            Description = "Aut consequatur aut quia perspiciatis ut consectetur odio. Vel reiciendis assumenda consectetur. Quia hic quia dolorem est et quo vel. Quisquam non est sint.",
                            IsDeleted = true,
                            Name = "Aut numquam aut. Et est voluptatum. Quibusdam consequatur adipisci qui deserunt quos natus nobis ullam. Facere explicabo vel per",
                            UpdatedAt = new DateTime(2022, 8, 10, 21, 52, 31, 648, DateTimeKind.Unspecified).AddTicks(5825),
                            UpdatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04"
                        },
                        new
                        {
                            Id = "326fb39d-3047-4357-8cd2-669ce64db9b8",
                            CreatedAt = new DateTime(2022, 6, 27, 15, 24, 19, 961, DateTimeKind.Unspecified).AddTicks(7317),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "In eos qui omnis repellat. Ad aut eveniet est voluptatem quae. Repellendus doloribus et.",
                            IsDeleted = false,
                            Name = "Sunt voluptates voluptatibus officia. Ut natus optio ut dignissimos iusto doloremque ducimus quae. Ea nostrum id nihil odit ut t",
                            UpdatedAt = new DateTime(2022, 6, 27, 15, 24, 19, 961, DateTimeKind.Unspecified).AddTicks(7317),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "79b3faa3-2a38-4bc7-9e87-10b4ed32c651",
                            CreatedAt = new DateTime(2022, 2, 9, 6, 15, 46, 580, DateTimeKind.Unspecified).AddTicks(3667),
                            CreatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3",
                            Description = "Voluptatem magnam corporis doloribus voluptatum. Aut id expedita. Corrupti dolor laboriosam aut ipsum explicabo qui deserunt est provident. Quidem est consectetur dolor incidunt fuga. Ea laborum laudantium beatae nam et nobis. Laudantium numquam fugiat.",
                            IsDeleted = false,
                            Name = "Blanditiis cumque asperiores eos. Error autem fuga rem. Consequatur quod accusamus consequatur quas nisi fugiat molestiae minima",
                            UpdatedAt = new DateTime(2022, 2, 9, 6, 15, 46, 580, DateTimeKind.Unspecified).AddTicks(3667),
                            UpdatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3"
                        },
                        new
                        {
                            Id = "ade5346c-3732-45a0-b29c-76f32be74b81",
                            CreatedAt = new DateTime(2023, 5, 25, 3, 51, 42, 143, DateTimeKind.Unspecified).AddTicks(4526),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Ab reprehenderit doloribus. Nisi consectetur et sint veniam alias. Odio suscipit nisi tenetur.",
                            IsDeleted = false,
                            Name = "Aut rem autem cumque vitae ipsum est ea qui voluptatem. Voluptatem sit sequi amet repellat totam. Aut cupiditate earum vitae. Om",
                            UpdatedAt = new DateTime(2023, 5, 25, 3, 51, 42, 143, DateTimeKind.Unspecified).AddTicks(4526),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "54b709d2-1b9c-4952-96a5-e2fad6d58c52",
                            CreatedAt = new DateTime(2022, 9, 9, 4, 53, 0, 559, DateTimeKind.Unspecified).AddTicks(5682),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Culpa autem et vero adipisci nisi autem facilis. Sit est incidunt consequuntur eum reiciendis qui est delectus delectus. Nesciunt cupiditate numquam ipsam sed praesentium rerum occaecati.",
                            IsDeleted = false,
                            Name = "Voluptates non aut aut est fugiat. Aspernatur quis ipsa rerum nesciunt veritatis nesciunt ullam temporibus. Enim est ipsum minim",
                            UpdatedAt = new DateTime(2022, 9, 9, 4, 53, 0, 559, DateTimeKind.Unspecified).AddTicks(5682),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        });
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Prompt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tokens")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            Id = "b1e68666-1a74-4e79-94fa-838fdfe45b43",
                            CreatedAt = new DateTime(2023, 2, 25, 16, 55, 30, 230, DateTimeKind.Unspecified).AddTicks(1612),
                            CreatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890",
                            Description = "Neque non ut officia. Maiores fuga nisi sed ut minima quia et. Et aliquam modi molestiae inventore dolores nemo sed non. Cum totam voluptas quas ab qui nobis molestias nihil soluta.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Ut atque ipsum. Aut id fugiat. Ex eveniet voluptatem quia veniam\"},{\"role\":\"user\",\"content\":\"Delectus commodi eum. Consequatur dolores eius numquam accusanti\"},{\"role\":\"user\",\"content\":\"Consequatur perferendis qui quis ipsam laborum ut minus sint. Fa\"},{\"role\":\"system\",\"content\":\"Accusantium aut quis iure reiciendis sunt quasi. Quidem deserunt\"},{\"role\":\"user\",\"content\":\"Ut autem est a. Quia et fugiat. Numquam quia aut illum quis et q\"}]",
                            Model = "gpt-4",
                            Name = "Non blanditiis non consequatur reiciendis quo fugit sit nesciunt. Et repudiandae ut quis recusandae perferendis esse saepe commo",
                            ProjectId = "a223464d-0d09-46d8-92a8-39b5d41dbf9b",
                            Tokens = 6081,
                            UpdatedAt = new DateTime(2023, 2, 25, 16, 55, 30, 230, DateTimeKind.Unspecified).AddTicks(1612),
                            UpdatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890"
                        },
                        new
                        {
                            Id = "8ceda7ea-f577-483a-8779-24df63f98992",
                            CreatedAt = new DateTime(2022, 3, 14, 8, 46, 44, 243, DateTimeKind.Unspecified).AddTicks(6715),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Omnis alias soluta perferendis eveniet et voluptatum est quos non. Ut occaecati corporis velit molestias voluptatem. Recusandae nobis itaque optio. Voluptatem aut ut incidunt architecto. Eos voluptas sequi voluptatibus facere quibusdam sit numquam rerum qu",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Quod dolores optio qui velit provident dignissimos. Commodi cumq\"},{\"role\":\"system\",\"content\":\"Occaecati esse rem fugiat nulla ea. A quia reprehenderit eos et\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Molestias quos autem explicabo maxime voluptatum explicabo. Optio dolorem maxime laborum at nobis sunt aut quaerat. Ut debitis a",
                            ProjectId = "1ba33397-e4cc-48c2-9955-64c2aa4ee805",
                            Tokens = 1462,
                            UpdatedAt = new DateTime(2022, 3, 14, 8, 46, 44, 243, DateTimeKind.Unspecified).AddTicks(6715),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "c6f06591-2fbd-4aab-ba50-ccd0a74d12b6",
                            CreatedAt = new DateTime(2022, 7, 2, 2, 51, 30, 883, DateTimeKind.Unspecified).AddTicks(4811),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Facilis quo nobis molestiae aperiam dicta in veritatis impedit perferendis. Molestiae accusamus voluptatem. Sapiente eveniet omnis veniam. Suscipit at quam vel exercitationem impedit occaecati aspernatur. Non quia beatae praesentium excepturi magnam conseq",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Voluptatibus dolore possimus earum similique. Architecto quia co\"},{\"role\":\"system\",\"content\":\"Quod esse dolores. Praesentium sint delectus nulla quibusdam omn\"},{\"role\":\"assistant\",\"content\":\"Fugiat repudiandae aut commodi consequuntur eveniet. Molestias q\"}]",
                            Model = "gpt-4",
                            Name = "Eum necessitatibus voluptatem natus aliquam ea maiores. Et praesentium qui eligendi. Omnis non sapiente blanditiis voluptatem eu",
                            ProjectId = "84048d83-2704-4194-9f57-24c716a8508f",
                            Tokens = 15416,
                            UpdatedAt = new DateTime(2022, 7, 2, 2, 51, 30, 883, DateTimeKind.Unspecified).AddTicks(4811),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "0d6cab6f-f368-4420-9ced-9b3fde60d128",
                            CreatedAt = new DateTime(2023, 4, 12, 7, 57, 59, 283, DateTimeKind.Unspecified).AddTicks(8427),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Eum doloremque aut asperiores magnam. Ipsum error quis tenetur fugit exercitationem quod velit sed. Aut doloremque eveniet molestiae repellendus natus corporis at. Fuga est consequatur qui aperiam odit. Cupiditate modi ea ipsam fuga minus. Ut repellat volu",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Tenetur inventore beatae veritatis. Recusandae omnis necessitati\"},{\"role\":\"assistant\",\"content\":\"Et et aliquam ea ut autem recusandae perspiciatis. Voluptatem ne\"},{\"role\":\"user\",\"content\":\"Eum a omnis et sit omnis sit. Accusamus sequi et ut veritatis ad\"},{\"role\":\"assistant\",\"content\":\"Aliquam molestiae neque fuga ipsa quo ipsa quis. Minus commodi s\"},{\"role\":\"assistant\",\"content\":\"Laboriosam ratione maxime. Quis quae nam facilis inventore. Et m\"},{\"role\":\"system\",\"content\":\"Hic consequatur tempora id ducimus ut. Sit sed minus sapiente et\"},{\"role\":\"user\",\"content\":\"Aliquam fuga et. Dolore magnam at ipsam rem consequatur nostrum\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Eum ut possimus et. Voluptate non quia et consequatur ut maiores sequi minus. Eos libero vitae laboriosam qui illum voluptas ali",
                            ProjectId = "d7895405-ea42-4547-823c-386844994f8a",
                            Tokens = 367,
                            UpdatedAt = new DateTime(2023, 4, 12, 7, 57, 59, 283, DateTimeKind.Unspecified).AddTicks(8427),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "c56fedd0-808d-4490-a0fe-1e004acf4d2a",
                            CreatedAt = new DateTime(2023, 5, 27, 10, 44, 38, 535, DateTimeKind.Unspecified).AddTicks(4738),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Voluptatem velit quis quis qui. Ratione quas consequatur a dicta ducimus. Ut est sit pariatur incidunt provident alias temporibus. Molestiae et corporis repellendus rerum totam deserunt. Voluptas soluta quisquam omnis.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"Nulla qui soluta deleniti odio voluptatibus rerum autem eius qua\"},{\"role\":\"user\",\"content\":\"Quae a minima perferendis non quod debitis facere qui necessitat\"},{\"role\":\"system\",\"content\":\"Suscipit eius dignissimos et error rerum vel cupiditate voluptas\"},{\"role\":\"assistant\",\"content\":\"Sequi itaque sed perferendis enim non nisi accusamus quisquam. V\"},{\"role\":\"user\",\"content\":\"Voluptas in eum. Odit aperiam quisquam placeat numquam quis et e\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Inventore labore dolor dolor. Magni omnis libero. Ut eaque quae eum illo distinctio assumenda earum et. Quas molestiae repudiand",
                            ProjectId = "8d98fc40-1b5d-4e56-b1db-6a3381a284d9",
                            Tokens = 12622,
                            UpdatedAt = new DateTime(2023, 5, 27, 10, 44, 38, 535, DateTimeKind.Unspecified).AddTicks(4738),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "948d7250-9059-48b5-9d25-96cb26376a37",
                            CreatedAt = new DateTime(2022, 3, 11, 7, 3, 24, 953, DateTimeKind.Unspecified).AddTicks(4741),
                            CreatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04",
                            Description = "Repellendus est asperiores. Consequatur ea sit in deserunt vel est. Sed rerum aut amet voluptates laudantium. Distinctio doloribus repellendus dolore. Est qui dolorum eaque maiores. Iusto quaerat at odio ut est blanditiis.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"system\",\"content\":\"Minima eius at. Autem voluptate architecto occaecati ut ea rem v\"},{\"role\":\"system\",\"content\":\"Quidem soluta quidem voluptatem reprehenderit rem. Minus sequi e\"},{\"role\":\"user\",\"content\":\"Dicta mollitia alias soluta id voluptates. Natus aut quasi minim\"},{\"role\":\"assistant\",\"content\":\"Illum quaerat unde voluptatem nulla vitae. Quis earum debitis ip\"},{\"role\":\"system\",\"content\":\"Expedita qui sint dignissimos at. Doloremque culpa cumque tempor\"},{\"role\":\"user\",\"content\":\"Vel cumque rerum beatae velit fuga culpa dolores impedit blandit\"},{\"role\":\"system\",\"content\":\"Molestiae delectus architecto. Quo eos cum sint consectetur. Mol\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Harum voluptatum illum. Sint aperiam et voluptatem labore culpa quam tenetur. Vel consequatur culpa ut laudantium omnis rem reru",
                            ProjectId = "1cb87bd7-86c6-4d95-a152-9a54e91ed684",
                            Tokens = 13659,
                            UpdatedAt = new DateTime(2022, 3, 11, 7, 3, 24, 953, DateTimeKind.Unspecified).AddTicks(4741),
                            UpdatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04"
                        },
                        new
                        {
                            Id = "140e53ae-b417-4c8b-91f5-b758a5bd4cac",
                            CreatedAt = new DateTime(2022, 10, 19, 14, 5, 45, 847, DateTimeKind.Unspecified).AddTicks(476),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Iure incidunt qui sed ipsum minus eum esse assumenda esse. Repellendus ut quas. Nisi omnis aliquam vitae ipsum molestiae.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Laborum ut qui aperiam quidem veniam nemo fugiat. Minima qui id\"},{\"role\":\"user\",\"content\":\"Ut excepturi animi sequi vitae voluptas. Est dolor enim distinct\"},{\"role\":\"assistant\",\"content\":\"Quis officiis ex accusamus dolorem ea eveniet. Nobis et reiciend\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Praesentium repellat rerum. Et exercitationem incidunt sed quos. Ullam doloremque sunt quos quis maxime animi. Et ut voluptas se",
                            ProjectId = "326fb39d-3047-4357-8cd2-669ce64db9b8",
                            Tokens = 8024,
                            UpdatedAt = new DateTime(2022, 10, 19, 14, 5, 45, 847, DateTimeKind.Unspecified).AddTicks(476),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "64a8b5eb-23c4-4c31-a1bf-65deb5c8d8d5",
                            CreatedAt = new DateTime(2022, 9, 1, 23, 5, 27, 610, DateTimeKind.Unspecified).AddTicks(5563),
                            CreatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3",
                            Description = "Tempora culpa nihil nulla id aut non est nobis. Omnis a dolor et ab reiciendis sint. Et totam voluptate assumenda possimus ipsam.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Ratione et amet rerum. Minus saepe quia magnam. Numquam ducimus\"},{\"role\":\"system\",\"content\":\"Aspernatur atque non sit repudiandae est facere id est. Dolores\"},{\"role\":\"assistant\",\"content\":\"At enim magnam tempore quibusdam inventore ullam autem. Fugiat o\"},{\"role\":\"assistant\",\"content\":\"Ab quis sunt earum vitae enim nihil voluptas. Provident ullam ex\"},{\"role\":\"assistant\",\"content\":\"Consequatur ut quia numquam a voluptatem at aut. Quod nemo verit\"},{\"role\":\"user\",\"content\":\"Suscipit accusantium cumque voluptas quisquam consequatur eos ip\"},{\"role\":\"assistant\",\"content\":\"Maxime eius culpa voluptates. Est a distinctio. Minus corrupti e\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Ut velit amet velit officiis delectus ullam. Ad itaque recusandae nisi ut perferendis accusamus. Quaerat maiores aliquam dolorem",
                            ProjectId = "79b3faa3-2a38-4bc7-9e87-10b4ed32c651",
                            Tokens = 11742,
                            UpdatedAt = new DateTime(2022, 9, 1, 23, 5, 27, 610, DateTimeKind.Unspecified).AddTicks(5563),
                            UpdatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3"
                        },
                        new
                        {
                            Id = "423eb7f8-2827-43b3-90d4-d49d18bd6328",
                            CreatedAt = new DateTime(2023, 11, 28, 1, 10, 51, 664, DateTimeKind.Unspecified).AddTicks(4400),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Ipsa ut a at voluptates nisi quae unde. Vel explicabo in eum ut vel dolorum rerum soluta. Accusamus enim explicabo ipsum possimus nam voluptatum possimus et atque. Quibusdam omnis dolorum quia omnis in aut.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Qui voluptate veniam qui qui quaerat. Dignissimos harum commodi\"},{\"role\":\"user\",\"content\":\"Enim quam id labore aliquid temporibus nesciunt dolorem veniam.\"},{\"role\":\"user\",\"content\":\"Quo officia ipsa voluptas et ut. Ut est tempora ipsa quia dolore\"},{\"role\":\"system\",\"content\":\"Ipsum nesciunt quo iure velit et blanditiis. Aliquid ut numquam\"},{\"role\":\"system\",\"content\":\"Laborum hic dolor voluptatem. Cupiditate nihil maiores natus ape\"},{\"role\":\"system\",\"content\":\"Dolore odit laborum iste. At corrupti et eaque qui. Dolores ut q\"},{\"role\":\"assistant\",\"content\":\"Ducimus sed quasi et eveniet explicabo qui aliquam modi. Dolores\"},{\"role\":\"assistant\",\"content\":\"Aperiam consequuntur nostrum veritatis. Et eaque tempore est inv\"}]",
                            Model = "gpt-4",
                            Name = "Vitae molestiae quos alias modi quis eaque. Ut explicabo tempora ipsam sed quasi accusamus dolores adipisci quaerat. Blanditiis",
                            ProjectId = "ade5346c-3732-45a0-b29c-76f32be74b81",
                            Tokens = 15536,
                            UpdatedAt = new DateTime(2023, 11, 28, 1, 10, 51, 664, DateTimeKind.Unspecified).AddTicks(4400),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "6e1cff81-a27b-44bb-96cd-3114bf6e7924",
                            CreatedAt = new DateTime(2022, 11, 17, 5, 58, 0, 589, DateTimeKind.Unspecified).AddTicks(2596),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Aliquid veritatis consequuntur eum. A eum fugiat possimus. Facilis dolores inventore qui ab. Ut et dicta in quia consequatur eligendi aperiam tenetur. Esse vel rerum quae velit eos. Aut maiores debitis dolorem non qui velit aperiam sint laudantium.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Culpa nobis sunt. Corrupti perspiciatis totam consequuntur recus\"},{\"role\":\"assistant\",\"content\":\"Alias distinctio eligendi quidem labore dolores. Quo unde esse e\"},{\"role\":\"assistant\",\"content\":\"Rerum quo quam nobis corrupti in quas sed. Odit eum non et et ma\"},{\"role\":\"system\",\"content\":\"Consequuntur accusantium natus vero quasi nisi facilis voluptate\"},{\"role\":\"user\",\"content\":\"Id velit dicta ut doloribus rerum dignissimos quis. Ab recusanda\"},{\"role\":\"assistant\",\"content\":\"Rerum necessitatibus labore. Repellat modi soluta quod fugit. Vo\"},{\"role\":\"user\",\"content\":\"Voluptatem nesciunt dolores perspiciatis vel mollitia reiciendis\"}]",
                            Model = "gpt-4",
                            Name = "Officiis hic sed vitae veritatis facere qui dolorem sit. Atque facilis aperiam id. Dolorem ratione iste aliquam voluptatum. Et v",
                            ProjectId = "54b709d2-1b9c-4952-96a5-e2fad6d58c52",
                            Tokens = 267,
                            UpdatedAt = new DateTime(2022, 11, 17, 5, 58, 0, 589, DateTimeKind.Unspecified).AddTicks(2596),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "29336f12-9f4d-4465-8e78-b2fd48e504b6",
                            CreatedAt = new DateTime(2022, 6, 17, 12, 26, 46, 622, DateTimeKind.Unspecified).AddTicks(9206),
                            CreatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890",
                            Description = "Consequuntur velit aut quasi non aspernatur corporis eligendi. Eos deleniti assumenda molestias aliquid commodi ut et ullam. Et officia molestiae rerum repellat at cumque eum.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Excepturi debitis reprehenderit veniam ab voluptas inventore dol\"},{\"role\":\"system\",\"content\":\"Et eveniet eaque illum repellat nam corrupti assumenda et labore\"},{\"role\":\"system\",\"content\":\"Occaecati occaecati fuga. Architecto itaque sint deserunt et nec\"},{\"role\":\"assistant\",\"content\":\"Perspiciatis molestiae voluptates dolore. Sed officia aut aut au\"},{\"role\":\"system\",\"content\":\"Cum doloremque ut quidem tempora aut sequi maiores. Voluptas eiu\"},{\"role\":\"system\",\"content\":\"Odit officia omnis doloremque aut. Autem totam quas. Officia sed\"},{\"role\":\"assistant\",\"content\":\"Doloribus vero et dolores cum non laborum beatae dolores rerum.\"},{\"role\":\"system\",\"content\":\"Porro sed sapiente sint quo qui iusto. Explicabo accusamus molli\"},{\"role\":\"assistant\",\"content\":\"Rerum quae omnis dolorum. Qui praesentium omnis optio dolores co\"},{\"role\":\"assistant\",\"content\":\"Maiores reprehenderit consequatur error qui illum. Sint dolores\"}]",
                            Model = "gpt-4",
                            Name = "Laboriosam asperiores sint ipsum delectus. Accusamus omnis commodi eum minima cum aliquid. Deleniti iste quia labore impedit. Ma",
                            ProjectId = "a223464d-0d09-46d8-92a8-39b5d41dbf9b",
                            Tokens = 7963,
                            UpdatedAt = new DateTime(2022, 6, 17, 12, 26, 46, 622, DateTimeKind.Unspecified).AddTicks(9206),
                            UpdatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890"
                        },
                        new
                        {
                            Id = "f6dfacad-566f-41a2-ba26-19c931816c8d",
                            CreatedAt = new DateTime(2022, 6, 22, 10, 57, 20, 476, DateTimeKind.Unspecified).AddTicks(7131),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Repellendus architecto eum repellendus repellendus ab. Omnis dolore laboriosam sint soluta praesentium rerum sed natus. Nostrum ipsam aliquam nam aut est.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Error quas sed dolor. Quidem quia eligendi aut nam omnis omnis n\"},{\"role\":\"user\",\"content\":\"Debitis qui fugit facere voluptatem est qui vel. Quia doloribus\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Vel temporibus excepturi. Laborum ut non. Corrupti omnis eos id eos quod. Non aliquam et quia. Corporis recusandae velit eius ve",
                            ProjectId = "1ba33397-e4cc-48c2-9955-64c2aa4ee805",
                            Tokens = 8560,
                            UpdatedAt = new DateTime(2022, 6, 22, 10, 57, 20, 476, DateTimeKind.Unspecified).AddTicks(7131),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "b4133ea9-5867-460b-a7d4-0c339d0c7046",
                            CreatedAt = new DateTime(2022, 3, 14, 19, 5, 35, 579, DateTimeKind.Unspecified).AddTicks(4595),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Eveniet tempora voluptatem est quod. Et aperiam sint illum velit. Quidem expedita fugit quibusdam tenetur omnis facere non ex qui.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Unde ex facere adipisci doloremque quidem omnis cum. Sed id impe\"},{\"role\":\"system\",\"content\":\"Quis ut necessitatibus rerum rem qui quis magni quia repellendus\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Et quia incidunt suscipit fugiat sunt suscipit sunt autem perferendis. Ipsa quisquam quibusdam quia earum doloribus molestias du",
                            ProjectId = "84048d83-2704-4194-9f57-24c716a8508f",
                            Tokens = 15798,
                            UpdatedAt = new DateTime(2022, 3, 14, 19, 5, 35, 579, DateTimeKind.Unspecified).AddTicks(4595),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "03c36806-0790-4540-a96f-547d4c82aed4",
                            CreatedAt = new DateTime(2022, 9, 9, 16, 6, 47, 971, DateTimeKind.Unspecified).AddTicks(3316),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Quisquam ut tempora omnis modi perspiciatis. Id qui quaerat minus dolores at dignissimos voluptatem repudiandae. Quia qui consequatur tenetur voluptas necessitatibus nemo totam ea.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Recusandae illum amet sit cupiditate qui doloremque rerum rerum\"},{\"role\":\"system\",\"content\":\"Earum neque ut iure distinctio labore sunt. Omnis perferendis la\"},{\"role\":\"assistant\",\"content\":\"Qui eveniet at ut consequatur eos qui. Exercitationem eos ut per\"},{\"role\":\"assistant\",\"content\":\"Odit in est neque aut excepturi. Possimus ratione aut consequunt\"},{\"role\":\"user\",\"content\":\"Sed eligendi velit reiciendis maxime dolores distinctio. Volupta\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Qui minus minima rerum earum. Harum et commodi ratione adipisci. Voluptas velit recusandae omnis porro sequi. Ipsam aut tenetur",
                            ProjectId = "d7895405-ea42-4547-823c-386844994f8a",
                            Tokens = 2671,
                            UpdatedAt = new DateTime(2022, 9, 9, 16, 6, 47, 971, DateTimeKind.Unspecified).AddTicks(3316),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "08cdd86b-e1f4-45ff-9ba0-560d134b4cea",
                            CreatedAt = new DateTime(2022, 9, 13, 23, 54, 22, 971, DateTimeKind.Unspecified).AddTicks(7680),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Possimus temporibus vel fugit ut ad unde. Sint illum eaque quod modi esse enim blanditiis est. Nam sint qui hic quas ut rerum et nobis. Ex temporibus et.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"Nulla qui pariatur neque facilis reiciendis commodi porro id imp\"},{\"role\":\"assistant\",\"content\":\"Nisi voluptatibus non. Velit similique ipsum harum qui eum tempo\"},{\"role\":\"assistant\",\"content\":\"Iusto magnam sint. Suscipit occaecati sit ad aperiam. Repellat d\"},{\"role\":\"system\",\"content\":\"Aut quod quidem cumque perspiciatis aliquam. Qui rerum error et\"},{\"role\":\"user\",\"content\":\"Qui aut dolorem ex expedita modi nam repudiandae voluptatem. Dol\"},{\"role\":\"assistant\",\"content\":\"Deleniti odio occaecati impedit sunt iste et blanditiis quia cum\"}]",
                            Model = "gpt-4",
                            Name = "In minima quasi facilis omnis pariatur earum odio voluptatem magni. Molestiae adipisci magni esse. Asperiores perspiciatis corru",
                            ProjectId = "8d98fc40-1b5d-4e56-b1db-6a3381a284d9",
                            Tokens = 3209,
                            UpdatedAt = new DateTime(2022, 9, 13, 23, 54, 22, 971, DateTimeKind.Unspecified).AddTicks(7680),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "042a28d0-7e72-4cda-8fb9-88ea57909098",
                            CreatedAt = new DateTime(2022, 9, 14, 0, 37, 38, 137, DateTimeKind.Unspecified).AddTicks(8382),
                            CreatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04",
                            Description = "Sint qui optio laboriosam dolores reiciendis dolorem. Tempore et aliquam totam expedita sunt cum qui voluptatum sed. Est odio doloribus reprehenderit aut.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Saepe vel est veritatis. Eum aut dolor veniam. Sequi quia error\"},{\"role\":\"user\",\"content\":\"Vel sit voluptatem vero voluptatibus doloribus nulla omnis. Volu\"},{\"role\":\"system\",\"content\":\"Officia veritatis ut atque et omnis dolor magni. Expedita qui si\"},{\"role\":\"system\",\"content\":\"Dolor corporis rerum repellat. Non repudiandae quas. Velit recus\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Sed sint non magni ut unde. Quo molestiae adipisci nostrum accusantium quo deleniti officia. Voluptatibus numquam nostrum fuga c",
                            ProjectId = "1cb87bd7-86c6-4d95-a152-9a54e91ed684",
                            Tokens = 13396,
                            UpdatedAt = new DateTime(2022, 9, 14, 0, 37, 38, 137, DateTimeKind.Unspecified).AddTicks(8382),
                            UpdatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04"
                        },
                        new
                        {
                            Id = "ef620537-3c1f-41b7-a4f7-2dd5a864e893",
                            CreatedAt = new DateTime(2022, 9, 21, 6, 2, 39, 192, DateTimeKind.Unspecified).AddTicks(2146),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Fugit exercitationem veniam maiores enim. Laborum molestias velit sed. Amet inventore quibusdam dolorem nam numquam. Ut nam numquam. Doloribus placeat est tempora. Eius et voluptate et aspernatur.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"system\",\"content\":\"Sed ea doloremque doloribus cumque doloremque non nesciunt est u\"},{\"role\":\"system\",\"content\":\"Sapiente doloribus quia omnis. Modi sed qui quo unde corporis mo\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Delectus qui temporibus eveniet qui dignissimos. Delectus rerum incidunt numquam iure est. Ut quo id amet eos aut dolor et ipsa.",
                            ProjectId = "326fb39d-3047-4357-8cd2-669ce64db9b8",
                            Tokens = 3463,
                            UpdatedAt = new DateTime(2022, 9, 21, 6, 2, 39, 192, DateTimeKind.Unspecified).AddTicks(2146),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "e47fd54f-ef65-49f9-b1f6-38a198b43fe5",
                            CreatedAt = new DateTime(2022, 4, 10, 17, 46, 52, 973, DateTimeKind.Unspecified).AddTicks(1122),
                            CreatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3",
                            Description = "Id qui quia cumque rem fugit magnam ipsa. Voluptatem reiciendis excepturi voluptatem. Illum minima vel. Reiciendis illum laborum. Quia et labore totam quia ut et et minus. Aut incidunt ullam expedita natus perferendis debitis asperiores.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Et ducimus amet ut quibusdam. Occaecati magnam aliquid impedit o\"},{\"role\":\"system\",\"content\":\"Aut alias mollitia aspernatur veritatis dignissimos minima et mi\"},{\"role\":\"system\",\"content\":\"Non cum harum iure aut ea architecto non harum corporis. Dolore\"}]",
                            Model = "gpt-4",
                            Name = "Et corrupti reiciendis qui placeat. Voluptatem eveniet sunt dolor excepturi quas expedita at vel aut. Quia corrupti beatae est a",
                            ProjectId = "79b3faa3-2a38-4bc7-9e87-10b4ed32c651",
                            Tokens = 4069,
                            UpdatedAt = new DateTime(2022, 4, 10, 17, 46, 52, 973, DateTimeKind.Unspecified).AddTicks(1122),
                            UpdatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3"
                        },
                        new
                        {
                            Id = "9dfd1d21-f47b-4bb4-9de6-536edcfbff29",
                            CreatedAt = new DateTime(2023, 6, 22, 10, 47, 7, 227, DateTimeKind.Unspecified).AddTicks(9843),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Nobis quisquam in sequi fugit accusamus voluptatem non sed. Ut et officiis nobis mollitia qui iure quia. Esse et id. Laborum quod est. Sequi asperiores dolor aut error consequatur alias rerum consequatur reiciendis. Earum qui et enim id cupiditate non dolo",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"Sapiente neque dolorem qui illum quia. Repudiandae odio placeat\"},{\"role\":\"system\",\"content\":\"Autem eaque doloremque. Recusandae harum laborum aut non. Est cu\"},{\"role\":\"user\",\"content\":\"Sed sunt provident eum. Non fuga recusandae qui cupiditate et. V\"},{\"role\":\"user\",\"content\":\"Sed veritatis a illum. Ratione harum quos id. Odio magnam cum qu\"},{\"role\":\"system\",\"content\":\"Omnis reiciendis a hic molestiae. Fugiat ipsa excepturi fugiat n\"},{\"role\":\"assistant\",\"content\":\"Est vel sequi neque. Rerum corporis quas qui ut et mollitia. Arc\"},{\"role\":\"user\",\"content\":\"Quo reiciendis et voluptatibus consequatur praesentium est totam\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Quibusdam reprehenderit reprehenderit ut quia maiores ea repudiandae. Nam cupiditate ea omnis vero qui vel sed sed. Eius veniam",
                            ProjectId = "ade5346c-3732-45a0-b29c-76f32be74b81",
                            Tokens = 1768,
                            UpdatedAt = new DateTime(2023, 6, 22, 10, 47, 7, 227, DateTimeKind.Unspecified).AddTicks(9843),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "e2c6c8e6-8132-4053-8e37-d11dc473fc02",
                            CreatedAt = new DateTime(2022, 8, 27, 13, 58, 38, 867, DateTimeKind.Unspecified).AddTicks(2421),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Voluptatem ut ullam consequatur sunt natus quis. Eos at possimus in excepturi animi hic sed. Sequi qui aut aut necessitatibus.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Fugiat impedit aut aut minima rerum minus accusamus. Delectus es\"},{\"role\":\"user\",\"content\":\"Eum eligendi distinctio accusantium sint ad quod minus dolores.\"},{\"role\":\"assistant\",\"content\":\"Sed consectetur aut. Earum dolores quae. Dolores provident volup\"},{\"role\":\"system\",\"content\":\"Perferendis cumque et commodi id dolor. Eum provident maxime. Se\"}]",
                            Model = "gpt-4",
                            Name = "Delectus laboriosam quaerat sint sapiente voluptatem accusantium rerum fugit. Reprehenderit facere quia voluptatem dolor. Fugit",
                            ProjectId = "54b709d2-1b9c-4952-96a5-e2fad6d58c52",
                            Tokens = 15557,
                            UpdatedAt = new DateTime(2022, 8, 27, 13, 58, 38, 867, DateTimeKind.Unspecified).AddTicks(2421),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "f0817911-a123-4b3e-8945-050c562fde37",
                            CreatedAt = new DateTime(2023, 11, 1, 6, 9, 57, 171, DateTimeKind.Unspecified).AddTicks(9268),
                            CreatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890",
                            Description = "Eveniet eum quidem eaque. Qui aliquam sed dignissimos quasi. Fuga tenetur sapiente deleniti non expedita ullam quia. Quis aut ipsam sint enim. Omnis suscipit vel nisi officia.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Nihil rerum consectetur recusandae iusto eveniet. Qui voluptatem\"},{\"role\":\"assistant\",\"content\":\"Velit ea velit est libero quasi eveniet. Aut tenetur eaque quod\"},{\"role\":\"assistant\",\"content\":\"Officia tempore provident eius sint sed aspernatur natus. Quam a\"},{\"role\":\"system\",\"content\":\"Officiis voluptate quod similique dolore incidunt. Aliquid quisq\"},{\"role\":\"user\",\"content\":\"Deserunt explicabo doloribus dolore nihil voluptas tempore. Qui\"},{\"role\":\"user\",\"content\":\"Voluptas adipisci voluptas unde quia laudantium dolorem ea ut. D\"},{\"role\":\"system\",\"content\":\"Quos vel modi. Fugit nesciunt voluptatem amet rerum. Ut ipsum ea\"},{\"role\":\"assistant\",\"content\":\"Quas enim ipsum. Saepe in quaerat sequi voluptatem dolores ut cu\"}]",
                            Model = "gpt-4",
                            Name = "Non rerum dolorem est nam dolores quaerat nulla fugit. Dolorum veniam molestias omnis tenetur nemo qui delectus. Rerum voluptate",
                            ProjectId = "a223464d-0d09-46d8-92a8-39b5d41dbf9b",
                            Tokens = 6198,
                            UpdatedAt = new DateTime(2023, 11, 1, 6, 9, 57, 171, DateTimeKind.Unspecified).AddTicks(9268),
                            UpdatedById = "074ba6f7-9633-410f-bb53-6fd71c8eb890"
                        },
                        new
                        {
                            Id = "4cf093c2-4909-4d9c-908d-8bbd5a14413b",
                            CreatedAt = new DateTime(2022, 6, 24, 14, 7, 21, 850, DateTimeKind.Unspecified).AddTicks(419),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Voluptatibus qui consequatur molestiae omnis ipsum aut eum. Est quasi eaque et. Eum blanditiis adipisci quia natus qui. Nam sit alias sed accusamus aut modi quas earum optio. Voluptas accusamus vel ex cumque.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Temporibus ab ea aliquam. Laboriosam eum eaque qui voluptas quia\"},{\"role\":\"system\",\"content\":\"Animi molestiae quia odio. Pariatur veritatis consequatur. Imped\"},{\"role\":\"assistant\",\"content\":\"Non officiis et ut aut animi rerum. Dolor aut odit. Veritatis ev\"},{\"role\":\"system\",\"content\":\"Sequi fugit quod consectetur qui eveniet rerum debitis voluptate\"},{\"role\":\"user\",\"content\":\"In assumenda similique et hic quisquam vel quaerat illum deserun\"},{\"role\":\"assistant\",\"content\":\"Tempora et ut provident placeat doloribus fuga consequatur. Iste\"},{\"role\":\"user\",\"content\":\"Dicta voluptatem facere. Quia et possimus aut suscipit exercitat\"},{\"role\":\"system\",\"content\":\"Quia sit qui commodi officia. Vel ut molestiae tenetur dicta bea\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Et ipsa perferendis id velit nesciunt omnis commodi. Inventore qui et et nesciunt in. Reiciendis qui quisquam et. Ad deleniti se",
                            ProjectId = "1ba33397-e4cc-48c2-9955-64c2aa4ee805",
                            Tokens = 11852,
                            UpdatedAt = new DateTime(2022, 6, 24, 14, 7, 21, 850, DateTimeKind.Unspecified).AddTicks(419),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "83a74e66-0dc9-4f9b-a3e9-be5c62e19ca2",
                            CreatedAt = new DateTime(2022, 5, 3, 7, 41, 40, 473, DateTimeKind.Unspecified).AddTicks(318),
                            CreatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf",
                            Description = "Sit voluptas voluptates enim velit sapiente eaque excepturi sed. Nulla occaecati vero sunt et minima. Quas et odit est vitae est eaque et quia sit. Molestiae sed fugit voluptas consequatur quis reiciendis illo.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Quis impedit voluptatem qui. Nobis sequi et recusandae possimus\"},{\"role\":\"assistant\",\"content\":\"Quisquam placeat sint libero recusandae. Illum sint eos numquam.\"},{\"role\":\"user\",\"content\":\"Explicabo deleniti ratione maxime repellat aut. Illum corporis d\"},{\"role\":\"assistant\",\"content\":\"Corporis tempore velit ipsa voluptatem dolorem voluptas fugiat i\"},{\"role\":\"assistant\",\"content\":\"Tempora eos ut. Quae vel repellat nihil assumenda repellendus of\"},{\"role\":\"system\",\"content\":\"Molestias corporis suscipit. Et incidunt eum. Consectetur dolore\"},{\"role\":\"assistant\",\"content\":\"Expedita qui omnis sint enim id. Praesentium assumenda excepturi\"},{\"role\":\"user\",\"content\":\"Et sint incidunt iste nihil aliquid veniam repellat. Minima sit\"},{\"role\":\"assistant\",\"content\":\"Totam dolorem voluptatem deleniti sunt facere. Odit esse eligend\"},{\"role\":\"system\",\"content\":\"Deleniti sed quis provident sequi aut similique et incidunt qui.\"}]",
                            Model = "gpt-4",
                            Name = "Fugiat maiores numquam exercitationem sunt eum blanditiis neque id deserunt. Ullam eos officiis non sapiente voluptas ut. Rem sa",
                            ProjectId = "84048d83-2704-4194-9f57-24c716a8508f",
                            Tokens = 3198,
                            UpdatedAt = new DateTime(2022, 5, 3, 7, 41, 40, 473, DateTimeKind.Unspecified).AddTicks(318),
                            UpdatedById = "c93cb7cf-704c-4369-8323-b0d8680586cf"
                        },
                        new
                        {
                            Id = "97bce606-fe67-409e-86ae-3e0aa3a8be43",
                            CreatedAt = new DateTime(2023, 3, 9, 2, 36, 28, 823, DateTimeKind.Unspecified).AddTicks(5150),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Fugit expedita sed perspiciatis similique. Explicabo deserunt accusantium. Repudiandae commodi a ut et. Quo consequatur est maxime assumenda in.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Vel facilis officia rerum quo perspiciatis. Autem omnis autem no\"},{\"role\":\"assistant\",\"content\":\"Aut deleniti provident temporibus quos ex quibusdam vel fugit. U\"},{\"role\":\"assistant\",\"content\":\"Sit velit aut delectus illum quas. Ut magni possimus illum rerum\"},{\"role\":\"user\",\"content\":\"Itaque omnis ut doloribus aut voluptate molestias ut. Praesentiu\"},{\"role\":\"assistant\",\"content\":\"Facilis ipsa nihil blanditiis consequatur praesentium voluptatum\"},{\"role\":\"system\",\"content\":\"Ut iure magnam. Ab qui accusamus. Voluptas dolor odio placeat nu\"},{\"role\":\"assistant\",\"content\":\"Repellendus quia dolore sint rerum id quibusdam. Sit saepe quis\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Voluptates sapiente velit repudiandae accusantium sit sit maxime repellendus. Quae atque laboriosam molestias ipsum reprehenderi",
                            ProjectId = "d7895405-ea42-4547-823c-386844994f8a",
                            Tokens = 6254,
                            UpdatedAt = new DateTime(2023, 3, 9, 2, 36, 28, 823, DateTimeKind.Unspecified).AddTicks(5150),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "558059fc-ae73-4cc3-8704-6444682b47a2",
                            CreatedAt = new DateTime(2022, 1, 5, 5, 22, 17, 155, DateTimeKind.Unspecified).AddTicks(8423),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Nihil culpa voluptatum et adipisci necessitatibus ut doloremque. Architecto rerum suscipit ipsam autem. Neque reprehenderit veritatis provident voluptas. Dolores quasi eos non nemo omnis. Modi ab eligendi culpa et provident suscipit aspernatur nihil occaec",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Velit ut minima. Iste ipsa aut voluptatem suscipit praesentium.\"},{\"role\":\"assistant\",\"content\":\"Magnam odio rerum doloribus omnis aut rem magnam ut itaque. Eaqu\"}]",
                            Model = "gpt-4",
                            Name = "In eos nam exercitationem voluptatem aut eos quisquam ut. Repellat et nemo cupiditate molestiae rerum impedit sunt vel dolorem.",
                            ProjectId = "8d98fc40-1b5d-4e56-b1db-6a3381a284d9",
                            Tokens = 14533,
                            UpdatedAt = new DateTime(2022, 1, 5, 5, 22, 17, 155, DateTimeKind.Unspecified).AddTicks(8423),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "dbcad1dd-e4e7-478a-b442-95538ece7b54",
                            CreatedAt = new DateTime(2022, 10, 29, 19, 53, 51, 941, DateTimeKind.Unspecified).AddTicks(6587),
                            CreatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04",
                            Description = "Iure deleniti dolorum velit nulla expedita vel nihil ex corporis. Maiores fugit sunt aut ut qui quo eum. Porro sunt veniam voluptate dolorem fugiat neque eligendi.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Consequatur sapiente aliquid molestiae quasi eveniet minus liber\"},{\"role\":\"user\",\"content\":\"Dolorum quis quaerat ipsum. Vitae et rerum. Ex et aspernatur qui\"},{\"role\":\"system\",\"content\":\"Cum occaecati quis quod minima maxime nostrum illum. Inventore s\"},{\"role\":\"assistant\",\"content\":\"Aut architecto rerum et eos cupiditate et at cum et. Beatae vel\"},{\"role\":\"user\",\"content\":\"Vitae ut fugiat. Quia nisi facilis optio maxime aut voluptas nob\"},{\"role\":\"system\",\"content\":\"Itaque blanditiis non consequatur quis minima in atque necessita\"},{\"role\":\"user\",\"content\":\"Excepturi quisquam qui animi possimus sed. Quis beatae tempore i\"},{\"role\":\"assistant\",\"content\":\"Vel autem adipisci. Consequatur ut natus. Ab impedit dolores mol\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Ea et et rerum nihil. Quam sint voluptatem et. Voluptatem ut veniam aspernatur rerum pariatur deleniti. Quos sed non molestiae m",
                            ProjectId = "1cb87bd7-86c6-4d95-a152-9a54e91ed684",
                            Tokens = 14284,
                            UpdatedAt = new DateTime(2022, 10, 29, 19, 53, 51, 941, DateTimeKind.Unspecified).AddTicks(6587),
                            UpdatedById = "e261f625-3e8a-422f-84c9-94bc09b14c04"
                        },
                        new
                        {
                            Id = "ce772031-9295-4571-b4d8-dfc36e279a2d",
                            CreatedAt = new DateTime(2023, 6, 25, 11, 25, 15, 387, DateTimeKind.Unspecified).AddTicks(1830),
                            CreatedById = "b4237756-952a-4df5-b069-3d5efa3db87b",
                            Description = "Fugiat possimus molestiae ex quis. Voluptas voluptate soluta quod minima qui. Soluta tempora dolorem autem et. Molestias eaque voluptatem culpa explicabo quia id consequatur voluptatum vero.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Qui pariatur laudantium odit est est aspernatur suscipit odio qu\"},{\"role\":\"system\",\"content\":\"Doloremque et eligendi necessitatibus qui ad id vel. Nesciunt ut\"},{\"role\":\"assistant\",\"content\":\"Ducimus quis itaque voluptas perferendis explicabo culpa alias d\"},{\"role\":\"user\",\"content\":\"Impedit rerum dolor commodi reprehenderit impedit autem consecte\"}]",
                            Model = "gpt-4",
                            Name = "Ut aliquid a. Eum ratione sit ipsum unde dignissimos facere. Culpa reiciendis voluptates velit nesciunt est est.",
                            ProjectId = "326fb39d-3047-4357-8cd2-669ce64db9b8",
                            Tokens = 5932,
                            UpdatedAt = new DateTime(2023, 6, 25, 11, 25, 15, 387, DateTimeKind.Unspecified).AddTicks(1830),
                            UpdatedById = "b4237756-952a-4df5-b069-3d5efa3db87b"
                        },
                        new
                        {
                            Id = "915ef70f-f48d-4a52-8716-586f7092690e",
                            CreatedAt = new DateTime(2023, 3, 30, 1, 40, 46, 212, DateTimeKind.Unspecified).AddTicks(5212),
                            CreatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3",
                            Description = "Quo voluptatem aperiam explicabo ea incidunt. Numquam quas est molestiae sit. Quos vel est doloremque a laboriosam rerum. Nihil ducimus quod qui.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Nisi totam dolorem placeat numquam aliquid. Minima dolorem eos f\"},{\"role\":\"assistant\",\"content\":\"Veniam autem ea sit omnis et rem sit repellendus saepe. Magni be\"},{\"role\":\"system\",\"content\":\"Est nostrum necessitatibus quia quia. Quod minus nihil laudantiu\"},{\"role\":\"user\",\"content\":\"Est totam aliquid saepe alias. Odit placeat voluptate quasi quam\"},{\"role\":\"user\",\"content\":\"Sint nihil delectus perspiciatis est alias optio tempora. Quis c\"},{\"role\":\"user\",\"content\":\"Esse eius enim occaecati quis voluptas laudantium eum nihil. Eve\"},{\"role\":\"assistant\",\"content\":\"At quidem inventore sunt suscipit quidem sunt est. Velit illum q\"},{\"role\":\"user\",\"content\":\"Autem adipisci architecto et veritatis velit dolorum. Dolorem et\"},{\"role\":\"system\",\"content\":\"Qui repellendus est tempora qui quia a ratione. Provident aut ac\"},{\"role\":\"assistant\",\"content\":\"Voluptate modi eligendi ducimus. Deleniti laboriosam debitis ita\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Fugiat eum sint reprehenderit est at. Magni debitis laboriosam at. Recusandae porro iste sint.",
                            ProjectId = "79b3faa3-2a38-4bc7-9e87-10b4ed32c651",
                            Tokens = 1938,
                            UpdatedAt = new DateTime(2023, 3, 30, 1, 40, 46, 212, DateTimeKind.Unspecified).AddTicks(5212),
                            UpdatedById = "9c37ec7e-4044-42bd-bfaa-ac6d2ae768c3"
                        },
                        new
                        {
                            Id = "56db8950-8982-4014-9431-174ea13b1e91",
                            CreatedAt = new DateTime(2022, 10, 24, 0, 51, 33, 288, DateTimeKind.Unspecified).AddTicks(9628),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Non quia natus odit unde et est provident. Ut accusamus quasi aut impedit dolore. Culpa iusto et quia quo. Enim quaerat suscipit est dicta minima doloribus qui iure aut.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Aut quia at. Quidem sit laborum doloremque eligendi libero est d\"},{\"role\":\"assistant\",\"content\":\"Illum repellendus dolores voluptate dolor et enim. Et quia eos q\"},{\"role\":\"assistant\",\"content\":\"Dolore est perspiciatis voluptates consequatur. Sint et perspici\"},{\"role\":\"assistant\",\"content\":\"Ipsum voluptatibus vitae animi aut consequatur. Aspernatur sint\"},{\"role\":\"assistant\",\"content\":\"Eos culpa qui voluptatem est quia aut. Non aut voluptates repell\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Qui consequatur voluptatem non eius officiis consequatur dolor. Qui fugiat est voluptatem ut fuga similique molestiae veniam. Te",
                            ProjectId = "ade5346c-3732-45a0-b29c-76f32be74b81",
                            Tokens = 15640,
                            UpdatedAt = new DateTime(2022, 10, 24, 0, 51, 33, 288, DateTimeKind.Unspecified).AddTicks(9628),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        },
                        new
                        {
                            Id = "ec862e61-a7f4-4246-97a6-311981881587",
                            CreatedAt = new DateTime(2022, 3, 4, 1, 12, 2, 429, DateTimeKind.Unspecified).AddTicks(6498),
                            CreatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c",
                            Description = "Ad ut totam quos. Consectetur aut ex optio quas facilis. Cupiditate quia aut ut atque adipisci saepe quis. Ea qui maiores quis vel. Id quia optio odio vel modi ducimus.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Eligendi dolore quos. Facere vero dolor quasi dolores. Ullam duc\"},{\"role\":\"assistant\",\"content\":\"Nihil et aperiam expedita aliquid sint consequatur occaecati. Cu\"},{\"role\":\"assistant\",\"content\":\"Aperiam enim sapiente fugit. Quia quidem aliquid non iusto quae\"},{\"role\":\"assistant\",\"content\":\"Voluptas velit et velit architecto est cupiditate. Quo ipsa susc\"}]",
                            Model = "gpt-4",
                            Name = "Suscipit natus non neque quia adipisci vel. Et commodi incidunt quo qui voluptas delectus perspiciatis nesciunt ipsam. Ut earum",
                            ProjectId = "54b709d2-1b9c-4952-96a5-e2fad6d58c52",
                            Tokens = 4690,
                            UpdatedAt = new DateTime(2022, 3, 4, 1, 12, 2, 429, DateTimeKind.Unspecified).AddTicks(6498),
                            UpdatedById = "d059dd1e-45f7-4522-85c1-a7bf2147574c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Project", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Prompt", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptHub2.Server.Models.Project", "Project")
                        .WithMany("Prompts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Project", b =>
                {
                    b.Navigation("Prompts");
                });
#pragma warning restore 612, 618
        }
    }
}
