// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptHub2.Server.Data;

#nullable disable

namespace PromptHub2.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231208142038_LowerCaseLettersInMessagesJSON")]
    partial class LowerCaseLettersInMessagesJSON
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "45539e43-6d1a-4506-9b7f-2a30610c0008",
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d95206ff-e272-4ea2-817c-887b933f41da",
                            Email = "Royal_Toy92@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ0VqT7lg2wYFE+mE/JKPliWqQjUJm0ZRfuYpokqO/wesEQmtwTj+J8/eX11TnLeNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "de95d2e1-a0f0-45be-980a-cc35bd90f10e",
                            TwoFactorEnabled = false,
                            UserName = "Royal_Toy92@gmail.com"
                        },
                        new
                        {
                            Id = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0df663d3-d2e5-4876-952a-bfae003aaf13",
                            Email = "Brando.Balistreri@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMLtgW7YBaO+ER3UmUljHhRg7+BuKgzhj7tA1gsaGEUVoiu1nGcVBh45mpA71HugSg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c6aa368-f0a2-4fd4-85a7-32aa046093c0",
                            TwoFactorEnabled = false,
                            UserName = "Brando.Balistreri@hotmail.com"
                        },
                        new
                        {
                            Id = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "788a4a8f-d78c-4ea5-b7b1-ab6a0c044782",
                            Email = "Maiya29@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEN3heGrfXiGgXKDPGaRVrYuVZpN5afaTBJgcydq/MVf+0Qj1CotDVz3n5PBhGRd9Tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea64fe63-3bdb-4e39-b60f-c540e6e32fb4",
                            TwoFactorEnabled = false,
                            UserName = "Maiya29@yahoo.com"
                        },
                        new
                        {
                            Id = "13ee4105-45c5-4c2c-8ebe-0da1d7604088",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "068d1862-b2c9-4385-bf11-fd7f05a3c859",
                            Email = "Reilly11@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEP8VmjBjGuscopLXQNzpWG/wxFvJMupY07ZdSQ+8zw+nyFcu1J37+S0giJWD6c0RWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "531d35a9-af7f-48a7-a2a1-1439541ce173",
                            TwoFactorEnabled = false,
                            UserName = "Reilly11@yahoo.com"
                        },
                        new
                        {
                            Id = "1032ce96-5386-4e95-b212-0b6446fb822b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d491272e-b01f-4f1d-a1ea-d169c309d8de",
                            Email = "Diana.Wiegand@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELt6YT/ZHgV/ull/pt/kRMkLBvaLpMCEJ3LTiV5Js6zvYbxBal7sb1bjh+1Mp6mpTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aaf48bc8-3dd7-41e7-8cea-b04746d59c61",
                            TwoFactorEnabled = false,
                            UserName = "Diana.Wiegand@gmail.com"
                        },
                        new
                        {
                            Id = "2405638c-5295-48e0-a232-75a22ac9c1fd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a32580b0-0ebc-495c-8de0-546969dcb545",
                            Email = "Evangeline_Spencer72@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKAiGeNPbdSo4f3JZFdMaxIhdWCBOOWk+R6WrFsbozsI5AqbIEERgAn3a7TYMkCUAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f657bf37-9c01-4b30-91f1-39e3f4a0219b",
                            TwoFactorEnabled = false,
                            UserName = "Evangeline_Spencer72@hotmail.com"
                        },
                        new
                        {
                            Id = "dd767247-16e5-41c9-a0d2-d5f9883146ef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f356f3bc-399f-4a78-a627-09f1541a0318",
                            Email = "Dante.Gusikowski@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOa7CbzNURD5GRwCGlDMYSWg9q9+n7jdrt11StqvI0IWIYCJtJKsPiMrehp1cHoqxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d08c1218-4c7b-43e9-9464-237cc835ff55",
                            TwoFactorEnabled = false,
                            UserName = "Dante.Gusikowski@gmail.com"
                        },
                        new
                        {
                            Id = "f524888c-56f3-4d04-be92-fe6b4f895b12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce991acd-7fec-44d8-93a4-d128387d62f7",
                            Email = "Hobart_Mills@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEH8fS9NTD1mv1a/kuZYoE/MzXqZsqGDrPemPlnxOwPfy3iNNnhsFY57Gsbo/grniVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db5135a6-1562-42c2-a180-b7f4f8c53c5c",
                            TwoFactorEnabled = false,
                            UserName = "Hobart_Mills@gmail.com"
                        },
                        new
                        {
                            Id = "9aef1613-965e-4579-9b03-95c05a90b0e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "274285e1-8d2d-4f35-9151-08f736fe23ab",
                            Email = "Florida.Predovic@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEK2PDwcPBU7G5QD3tL9U8eaFa2k8mFq/uqvRmsoTvEesVkmkSZeMmvwwN9EvecgoSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c842999d-9ac2-4614-9847-8070e968cdae",
                            TwoFactorEnabled = false,
                            UserName = "Florida.Predovic@hotmail.com"
                        },
                        new
                        {
                            Id = "e79ba770-a43f-4069-b95f-ad60a62320c9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d343668-71f7-4d03-a21e-7877d7539af2",
                            Email = "Zakary.Rath@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPsm62LeVjSykIixBHUV3U/LBdyqAp7+SiMguxoGLRbRuhJAntnkkeJw8DS7fldrgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "437c720a-27ab-4530-811c-670cf9a0493c",
                            TwoFactorEnabled = false,
                            UserName = "Zakary.Rath@yahoo.com"
                        },
                        new
                        {
                            Id = "141c219a-5f2d-4a3d-a3d0-d655eab6b36f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e551562c-388d-4f68-925b-bdf6ba861e05",
                            Email = "fi.kwiatkowski@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECV4Ohh9Amozwstt9DvoRiOKy0uKnqgQEd7derOnuV4rRZKm+oxoEpdoIxrbufy2gg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47f43953-0ded-4b49-a894-593fac0b02a1",
                            TwoFactorEnabled = false,
                            UserName = "fi.kwiatkowski@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "141c219a-5f2d-4a3d-a3d0-d655eab6b36f",
                            RoleId = "45539e43-6d1a-4506-9b7f-2a30610c0008"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "85d978b2-2dbb-4fe0-adf9-d0d5657d868a",
                            CreatedAt = new DateTime(2023, 3, 1, 3, 45, 17, 5, DateTimeKind.Unspecified).AddTicks(3979),
                            CreatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef",
                            Description = "Dignissimos delectus sit ut. Labore nemo impedit aperiam culpa occaecati veniam possimus ullam. Aliquid quas totam nihil fugiat in itaque rerum asperiores. Esse cupiditate nostrum quis cumque dignissimos. Velit voluptatem voluptatum expedita. Fugit dolores",
                            IsDeleted = true,
                            Name = "Velit harum quas voluptatum deleniti provident. Autem aut atque ipsa nulla quia voluptatem voluptate. Eius aut sed. Velit et aut",
                            UpdatedAt = new DateTime(2023, 3, 1, 3, 45, 17, 5, DateTimeKind.Unspecified).AddTicks(3979),
                            UpdatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef"
                        },
                        new
                        {
                            Id = "02490e24-e61f-40d0-b1ce-f604d5435c87",
                            CreatedAt = new DateTime(2022, 3, 22, 12, 30, 48, 152, DateTimeKind.Unspecified).AddTicks(9857),
                            CreatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088",
                            Description = "Quis deleniti sunt eaque assumenda aut autem assumenda rerum. Veniam consequatur eveniet ut vero voluptatem reiciendis non expedita. Recusandae eligendi nostrum tempora rerum architecto debitis ut nemo et. Saepe et qui id dignissimos eos.",
                            IsDeleted = false,
                            Name = "Itaque aut et fuga non. Necessitatibus neque harum ipsam ut facilis eaque quasi omnis. Laborum aut totam. Rem assumenda aliquam",
                            UpdatedAt = new DateTime(2022, 3, 22, 12, 30, 48, 152, DateTimeKind.Unspecified).AddTicks(9857),
                            UpdatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088"
                        },
                        new
                        {
                            Id = "d46499b9-1bdd-4c01-98be-9d9bbd560d68",
                            CreatedAt = new DateTime(2022, 4, 15, 2, 57, 12, 430, DateTimeKind.Unspecified).AddTicks(5610),
                            CreatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2",
                            Description = "Iusto omnis numquam eum. Eaque itaque iusto recusandae placeat necessitatibus unde repellendus. Voluptatem qui enim qui eaque.",
                            IsDeleted = false,
                            Name = "Consequuntur adipisci repudiandae voluptatibus commodi vero facilis deserunt itaque. Distinctio et laboriosam voluptas at eius i",
                            UpdatedAt = new DateTime(2022, 4, 15, 2, 57, 12, 430, DateTimeKind.Unspecified).AddTicks(5610),
                            UpdatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2"
                        },
                        new
                        {
                            Id = "771c3266-ab4d-411b-b2ed-35a6eeb01e83",
                            CreatedAt = new DateTime(2022, 6, 1, 5, 13, 35, 559, DateTimeKind.Unspecified).AddTicks(6180),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Sunt consequatur rerum qui quos et omnis quam. Et esse ducimus nihil rerum provident. Et odio voluptas dignissimos ad in quae. Et sint error neque. Dolorum et accusantium quos quas omnis eaque. Qui aliquid error.",
                            IsDeleted = true,
                            Name = "Sed est aspernatur. Porro soluta magni sapiente molestias nesciunt officiis. Atque voluptatem natus non. Et aperiam laborum earu",
                            UpdatedAt = new DateTime(2022, 6, 1, 5, 13, 35, 559, DateTimeKind.Unspecified).AddTicks(6180),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "9ee31024-e1e8-499e-89cb-1676e9872e32",
                            CreatedAt = new DateTime(2023, 1, 28, 9, 26, 42, 294, DateTimeKind.Unspecified).AddTicks(8370),
                            CreatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12",
                            Description = "Delectus est et adipisci nostrum beatae maxime sapiente. Velit est voluptatem quisquam laboriosam hic ducimus nesciunt sint. Aperiam est quis adipisci atque optio. Cupiditate culpa quas dolore asperiores non voluptatibus. Tempore harum est inventore.",
                            IsDeleted = false,
                            Name = "Dignissimos minima ipsa laboriosam itaque. Modi omnis rerum porro. Id et vitae beatae et harum dicta sed debitis. Nam velit fuga",
                            UpdatedAt = new DateTime(2023, 1, 28, 9, 26, 42, 294, DateTimeKind.Unspecified).AddTicks(8370),
                            UpdatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12"
                        },
                        new
                        {
                            Id = "f5f16745-8600-4a22-b864-4d86f1262478",
                            CreatedAt = new DateTime(2022, 3, 13, 14, 40, 36, 37, DateTimeKind.Unspecified).AddTicks(3617),
                            CreatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9",
                            Description = "Aspernatur qui officiis. Aspernatur id ea est et qui quam natus. Esse cupiditate omnis magni molestiae possimus ea architecto dolores. Alias aut autem sunt rem commodi est itaque numquam est.",
                            IsDeleted = false,
                            Name = "Impedit magni quaerat. Nihil sunt nihil nulla quo. Exercitationem consequuntur doloremque.",
                            UpdatedAt = new DateTime(2022, 3, 13, 14, 40, 36, 37, DateTimeKind.Unspecified).AddTicks(3617),
                            UpdatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9"
                        },
                        new
                        {
                            Id = "2a3eec74-b118-41fc-99aa-f7a8b0b6b62c",
                            CreatedAt = new DateTime(2022, 4, 1, 6, 5, 51, 225, DateTimeKind.Unspecified).AddTicks(2597),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Eos quae alias aliquam iste. Molestias esse atque blanditiis similique sequi eius. Fugiat explicabo vero eaque neque in accusamus maxime. Eveniet porro doloribus sit non nemo tempore culpa et at.",
                            IsDeleted = true,
                            Name = "Voluptatibus beatae et et deserunt ea. Magni illum eos temporibus est. Corporis quis et ut quia explicabo quos. Omnis temporibus",
                            UpdatedAt = new DateTime(2022, 4, 1, 6, 5, 51, 225, DateTimeKind.Unspecified).AddTicks(2597),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        },
                        new
                        {
                            Id = "f75b9f22-1cf4-4c0d-a838-05525371fa44",
                            CreatedAt = new DateTime(2023, 3, 3, 2, 56, 17, 959, DateTimeKind.Unspecified).AddTicks(9018),
                            CreatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd",
                            Description = "Magni rerum nobis dolor quos deserunt et omnis cupiditate rem. Sed et nisi dolores. Non similique repudiandae. Officiis sunt temporibus suscipit ut qui. Velit qui consequuntur ullam voluptatem quae et provident.",
                            IsDeleted = true,
                            Name = "Nihil ab nam perferendis dolor et pariatur autem. Et aliquid necessitatibus velit suscipit et suscipit inventore sint non. Maxim",
                            UpdatedAt = new DateTime(2023, 3, 3, 2, 56, 17, 959, DateTimeKind.Unspecified).AddTicks(9018),
                            UpdatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd"
                        },
                        new
                        {
                            Id = "480b8043-b15d-4124-b5dc-e93e7717cf8f",
                            CreatedAt = new DateTime(2022, 5, 4, 6, 29, 30, 537, DateTimeKind.Unspecified).AddTicks(215),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Occaecati dolore voluptatum ut molestias eum. Eos culpa ab. Eum ut amet neque eos. Animi nesciunt ducimus ipsum reprehenderit ut. Recusandae eos a ad dolor.",
                            IsDeleted = false,
                            Name = "Quia dolores nesciunt. Quo ea occaecati autem nihil fugit sed. Dolor voluptatum praesentium excepturi ratione voluptatem. Optio",
                            UpdatedAt = new DateTime(2022, 5, 4, 6, 29, 30, 537, DateTimeKind.Unspecified).AddTicks(215),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "c3151aa7-60b9-4682-a800-98077c6cef31",
                            CreatedAt = new DateTime(2022, 2, 15, 23, 45, 6, 0, DateTimeKind.Unspecified).AddTicks(3881),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Doloribus culpa et ullam rerum eum qui voluptas possimus iure. Qui exercitationem magni nemo. Magni quasi dolores eum et ab et velit. Eum sit nesciunt eum enim ratione explicabo. Omnis provident ut qui suscipit quaerat.",
                            IsDeleted = true,
                            Name = "Sunt rerum aspernatur repellendus non animi voluptatibus fuga quo. Repellendus fuga aut aut atque illo mollitia. Quaerat recusan",
                            UpdatedAt = new DateTime(2022, 2, 15, 23, 45, 6, 0, DateTimeKind.Unspecified).AddTicks(3881),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        });
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Prompt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tokens")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            Id = "cccdcef1-d086-41f6-b72d-fb348da06989",
                            CreatedAt = new DateTime(2023, 2, 17, 17, 6, 0, 607, DateTimeKind.Unspecified).AddTicks(7094),
                            CreatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef",
                            Description = "Est eos voluptatem commodi explicabo rerum ut sapiente. Placeat et beatae molestiae sint sint quia fugiat. Saepe veniam fugit sunt nisi quod molestias.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Impedit hic eius facilis dolorem necessitatibus perferendis. Mol\"},{\"role\":\"assistant\",\"content\":\"Rerum aut mollitia placeat eaque dignissimos. Nulla enim numquam\"},{\"role\":\"system\",\"content\":\"Recusandae reiciendis distinctio suscipit ullam quia non. Nulla\"},{\"role\":\"user\",\"content\":\"Perferendis cum laudantium dolores dolor nobis quasi autem liber\"},{\"role\":\"user\",\"content\":\"Inventore aut perferendis. Explicabo quae est non aut. Deserunt\"},{\"role\":\"system\",\"content\":\"Eum odio id. Perferendis et ipsum unde molestiae asperiores. Off\"}]",
                            Model = "gpt-4",
                            Name = "Sit quia provident sint. Architecto et provident sapiente autem quia. Ullam ea accusamus quidem. Velit deserunt sed pariatur vel",
                            ProjectId = "85d978b2-2dbb-4fe0-adf9-d0d5657d868a",
                            Tokens = 15071,
                            UpdatedAt = new DateTime(2023, 2, 17, 17, 6, 0, 607, DateTimeKind.Unspecified).AddTicks(7094),
                            UpdatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef"
                        },
                        new
                        {
                            Id = "487b7cfb-6066-4e0f-9bf7-881040d10869",
                            CreatedAt = new DateTime(2023, 3, 25, 1, 22, 3, 356, DateTimeKind.Unspecified).AddTicks(1307),
                            CreatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088",
                            Description = "Blanditiis consequuntur quasi qui est. Qui error vel sed ut sunt officia et. Consequatur itaque voluptatibus est at nostrum culpa cumque expedita.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Rerum accusamus id commodi est sit recusandae corrupti. Corrupti\"},{\"role\":\"system\",\"content\":\"Laudantium sint est aperiam laboriosam vitae. Voluptatum nisi au\"},{\"role\":\"user\",\"content\":\"Ut omnis harum pariatur voluptas sit. Quam et inventore autem. Q\"},{\"role\":\"assistant\",\"content\":\"Nam et et. Explicabo et ut eos omnis rerum harum. Consequatur ve\"}]",
                            Model = "gpt-4",
                            Name = "Iste delectus quis explicabo voluptate cupiditate eum iste recusandae. Magnam accusamus temporibus commodi labore quia repudiand",
                            ProjectId = "02490e24-e61f-40d0-b1ce-f604d5435c87",
                            Tokens = 5801,
                            UpdatedAt = new DateTime(2023, 3, 25, 1, 22, 3, 356, DateTimeKind.Unspecified).AddTicks(1307),
                            UpdatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088"
                        },
                        new
                        {
                            Id = "31d673f1-53fd-4a59-a641-4ee1063306d1",
                            CreatedAt = new DateTime(2022, 12, 13, 4, 19, 55, 541, DateTimeKind.Unspecified).AddTicks(2034),
                            CreatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2",
                            Description = "Porro suscipit molestiae vel aut omnis aut itaque ut velit. Non molestiae nostrum in. Corporis ducimus eos necessitatibus laudantium aut maxime excepturi. Quia officiis provident quo est voluptatem. Quo impedit sit tenetur occaecati quas vitae.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Quia aut labore doloremque inventore. Nulla soluta commodi fugit\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Aut fugiat autem est assumenda sed. Delectus sit itaque fugiat ad delectus est. Totam consequatur molestiae suscipit id qui exer",
                            ProjectId = "d46499b9-1bdd-4c01-98be-9d9bbd560d68",
                            Tokens = 5983,
                            UpdatedAt = new DateTime(2022, 12, 13, 4, 19, 55, 541, DateTimeKind.Unspecified).AddTicks(2034),
                            UpdatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2"
                        },
                        new
                        {
                            Id = "560bb51e-2572-4747-9eea-9aecd189bdca",
                            CreatedAt = new DateTime(2022, 2, 2, 0, 34, 38, 550, DateTimeKind.Unspecified).AddTicks(9091),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Magni vel reprehenderit totam provident tempora quaerat non optio. Voluptas est accusamus minima. Sint velit ab ipsa recusandae. Omnis necessitatibus sequi vel harum distinctio quaerat nulla nam.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Nihil vero harum cumque in enim praesentium. Minus corrupti repe\"},{\"role\":\"user\",\"content\":\"Voluptatem molestiae officia. Optio ut rerum maxime molestias ve\"},{\"role\":\"system\",\"content\":\"Corporis fuga iure rerum voluptatibus rerum. Cum cum ad. Qui seq\"},{\"role\":\"system\",\"content\":\"Sit odio ea sunt recusandae enim accusantium veniam illum. Et se\"},{\"role\":\"assistant\",\"content\":\"Omnis explicabo dolores qui voluptatibus omnis voluptas voluptat\"},{\"role\":\"assistant\",\"content\":\"Atque dicta aut nobis illo nam id ipsa sit est. Quia placeat nul\"},{\"role\":\"user\",\"content\":\"Ut consequatur ut aliquam quasi itaque quis suscipit ipsum nemo.\"},{\"role\":\"system\",\"content\":\"Exercitationem porro quod omnis quae. Quaerat qui accusamus saep\"},{\"role\":\"user\",\"content\":\"Nihil autem quia qui expedita. Officiis a earum voluptates fuga\"}]",
                            Model = "gpt-4",
                            Name = "Dolor quaerat eaque exercitationem et voluptas rerum sed quae. Delectus praesentium ut nesciunt. Ut unde aliquam quo consequatur",
                            ProjectId = "771c3266-ab4d-411b-b2ed-35a6eeb01e83",
                            Tokens = 5715,
                            UpdatedAt = new DateTime(2022, 2, 2, 0, 34, 38, 550, DateTimeKind.Unspecified).AddTicks(9091),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "32bfe1fc-3438-42a3-9679-de6de2a510ae",
                            CreatedAt = new DateTime(2022, 11, 14, 19, 30, 56, 443, DateTimeKind.Unspecified).AddTicks(7765),
                            CreatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12",
                            Description = "Ut in harum expedita tempore maxime ipsam. Perferendis veniam numquam optio suscipit voluptatibus nesciunt iure ea. Ullam rerum omnis impedit corporis explicabo. Esse laboriosam repudiandae.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Ipsum labore iste eligendi eligendi nihil ullam dolore. Pariatur\"},{\"role\":\"system\",\"content\":\"Assumenda dolorem error ab voluptas dolor. Voluptatem velit adip\"},{\"role\":\"assistant\",\"content\":\"Quis quos dolores neque. Molestiae asperiores et quaerat. Iure i\"},{\"role\":\"user\",\"content\":\"Voluptatem minus accusantium sunt autem ex quaerat. Ipsam sed ip\"},{\"role\":\"assistant\",\"content\":\"Et ad voluptas incidunt saepe rerum officia perferendis et. Quas\"},{\"role\":\"user\",\"content\":\"Rerum unde quasi. Et id dicta dignissimos. Impedit praesentium i\"}]",
                            Model = "gpt-4",
                            Name = "Excepturi id modi. Aut dolore minima nisi dolore odio itaque debitis ea dignissimos. Vitae necessitatibus voluptatem cupiditate",
                            ProjectId = "9ee31024-e1e8-499e-89cb-1676e9872e32",
                            Tokens = 8771,
                            UpdatedAt = new DateTime(2022, 11, 14, 19, 30, 56, 443, DateTimeKind.Unspecified).AddTicks(7765),
                            UpdatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12"
                        },
                        new
                        {
                            Id = "6f969943-954b-49e1-9e20-6d1e2c767953",
                            CreatedAt = new DateTime(2022, 4, 4, 3, 53, 47, 279, DateTimeKind.Unspecified).AddTicks(3228),
                            CreatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9",
                            Description = "Hic fugiat impedit ut omnis aut. Soluta iusto consequuntur officia repellat aspernatur ut officia magnam. Minus eligendi et esse velit a. Veniam quam sit qui dicta dolores doloribus voluptas. Dolore iste ad atque animi.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"Eos eos quam consequatur sint et nihil. Officiis quam a architec\"},{\"role\":\"system\",\"content\":\"Architecto molestiae ipsam corrupti vel iure. Aut et ipsa nesciu\"},{\"role\":\"user\",\"content\":\"Fuga dignissimos delectus corrupti consequatur debitis et. Sit v\"},{\"role\":\"assistant\",\"content\":\"Quo numquam dolores dolor laudantium deserunt. Aperiam fuga dolo\"},{\"role\":\"user\",\"content\":\"Consequatur enim qui nisi consequuntur non amet qui quo. Dolorem\"},{\"role\":\"user\",\"content\":\"Sapiente quod est sint debitis voluptate dolorum provident. Dele\"},{\"role\":\"assistant\",\"content\":\"Sunt et aspernatur quas asperiores sed optio adipisci. Libero ra\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Saepe nostrum omnis. Laborum labore libero est sit ut nisi blanditiis modi illum. Ut occaecati dolores in velit amet velit harum",
                            ProjectId = "f5f16745-8600-4a22-b864-4d86f1262478",
                            Tokens = 9441,
                            UpdatedAt = new DateTime(2022, 4, 4, 3, 53, 47, 279, DateTimeKind.Unspecified).AddTicks(3228),
                            UpdatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9"
                        },
                        new
                        {
                            Id = "0a061869-5614-4609-a7f9-1ebfa719aa45",
                            CreatedAt = new DateTime(2023, 9, 25, 15, 11, 6, 482, DateTimeKind.Unspecified).AddTicks(3739),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Veniam odio odio. Blanditiis eaque repellendus sit culpa repudiandae. Aut deserunt id natus eum magni. Quis et cumque et commodi saepe qui. Voluptas earum aspernatur error.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"Inventore non possimus rem a amet enim sit. Et officiis et dolor\"},{\"role\":\"assistant\",\"content\":\"Quidem harum dolorem laborum odit iusto rem quia. Voluptatem tem\"},{\"role\":\"user\",\"content\":\"Tempora qui hic unde nostrum. Vero mollitia nulla omnis optio. F\"},{\"role\":\"system\",\"content\":\"Ad rerum pariatur in totam et. Id eum nulla recusandae voluptati\"},{\"role\":\"system\",\"content\":\"Quasi soluta dignissimos delectus molestias occaecati voluptatem\"},{\"role\":\"assistant\",\"content\":\"Dignissimos et itaque vitae ut veritatis eos illo blanditiis qui\"},{\"role\":\"system\",\"content\":\"Architecto accusantium consequuntur suscipit quisquam aut aliqui\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Repellendus velit earum nam qui dolores a. Autem veritatis assumenda quod qui dicta possimus sint necessitatibus praesentium. Ex",
                            ProjectId = "2a3eec74-b118-41fc-99aa-f7a8b0b6b62c",
                            Tokens = 11764,
                            UpdatedAt = new DateTime(2023, 9, 25, 15, 11, 6, 482, DateTimeKind.Unspecified).AddTicks(3739),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        },
                        new
                        {
                            Id = "cff1b582-e186-4807-a778-b3653f482e7a",
                            CreatedAt = new DateTime(2023, 11, 23, 20, 18, 47, 583, DateTimeKind.Unspecified).AddTicks(9042),
                            CreatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd",
                            Description = "Consequatur et illo id provident incidunt nam rem et. Expedita voluptates accusamus similique quos. Labore fuga rerum. Fuga sint autem quis sint incidunt aliquid fugiat iure illo.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Non hic ullam temporibus nostrum nisi. Vel ipsa magni saepe nost\"},{\"role\":\"assistant\",\"content\":\"Pariatur in rerum consequatur pariatur optio a quis. Ut vero ad.\"},{\"role\":\"user\",\"content\":\"Ut temporibus rerum ad ratione cum laboriosam voluptatem et. Opt\"},{\"role\":\"assistant\",\"content\":\"Et expedita quia. Esse placeat temporibus fuga repellat a qui. D\"},{\"role\":\"system\",\"content\":\"Voluptatem consequatur unde. Qui voluptas ad voluptatibus perspi\"},{\"role\":\"system\",\"content\":\"Cumque molestias aut id et suscipit doloremque repudiandae tempo\"},{\"role\":\"user\",\"content\":\"Tempore ad aut reiciendis id. Ut saepe eos laudantium quo animi\"},{\"role\":\"user\",\"content\":\"Voluptas omnis consequatur possimus fugiat ad. Nisi vel qui volu\"},{\"role\":\"system\",\"content\":\"Voluptatem repellat laudantium id illo quos sed ipsum ex. Mollit\"}]",
                            Model = "gpt-4",
                            Name = "Similique commodi dolor dignissimos debitis mollitia blanditiis accusamus dolor occaecati. Et adipisci et. Quo consequatur reici",
                            ProjectId = "f75b9f22-1cf4-4c0d-a838-05525371fa44",
                            Tokens = 14728,
                            UpdatedAt = new DateTime(2023, 11, 23, 20, 18, 47, 583, DateTimeKind.Unspecified).AddTicks(9042),
                            UpdatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd"
                        },
                        new
                        {
                            Id = "73260645-2ba6-48f0-82ec-44e5577153c7",
                            CreatedAt = new DateTime(2022, 12, 16, 17, 25, 39, 679, DateTimeKind.Unspecified).AddTicks(6618),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Necessitatibus perferendis voluptatem ea corrupti placeat ut ipsa sint. Laboriosam voluptas odit fugit est rerum ad eveniet placeat sit. Ex veniam ea nemo eos et quidem. Beatae esse repudiandae quis cupiditate. Expedita eos molestiae non cum temporibus dol",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Debitis quia non aspernatur ex. Sit accusamus unde maiores fuga\"},{\"role\":\"assistant\",\"content\":\"Aperiam voluptates libero. Voluptatum omnis quia maiores impedit\"},{\"role\":\"user\",\"content\":\"Possimus hic aut officia accusamus. Excepturi omnis fugiat sapie\"}]",
                            Model = "gpt-4",
                            Name = "Id voluptatibus quae voluptas. Sed sit dolorem ex reiciendis excepturi. Porro officiis nostrum facere quis nam est. Corporis pra",
                            ProjectId = "480b8043-b15d-4124-b5dc-e93e7717cf8f",
                            Tokens = 7892,
                            UpdatedAt = new DateTime(2022, 12, 16, 17, 25, 39, 679, DateTimeKind.Unspecified).AddTicks(6618),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "3e58cd86-f2a8-4619-b4b7-f6ee7a437926",
                            CreatedAt = new DateTime(2023, 2, 15, 22, 40, 52, 432, DateTimeKind.Unspecified).AddTicks(3052),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "In itaque doloribus facere incidunt velit officia. Optio quis minus. Recusandae natus ut veritatis libero consequuntur veritatis. Id veritatis animi quae.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Quo sit voluptas voluptatum est consequatur rem. Velit voluptate\"},{\"role\":\"user\",\"content\":\"Nihil impedit corrupti blanditiis quis nesciunt corporis nobis l\"},{\"role\":\"system\",\"content\":\"Consequatur rerum modi rerum et recusandae accusamus consectetur\"},{\"role\":\"assistant\",\"content\":\"Sint nobis harum. Officia et ut quos nemo voluptates laborum. La\"},{\"role\":\"assistant\",\"content\":\"Voluptas deleniti commodi distinctio voluptatem porro minima lab\"}]",
                            Model = "gpt-4",
                            Name = "Ut ut totam iusto odio nihil consequatur. Labore sed officia sed optio accusamus est ut et vel. Quis esse unde.",
                            ProjectId = "c3151aa7-60b9-4682-a800-98077c6cef31",
                            Tokens = 1960,
                            UpdatedAt = new DateTime(2023, 2, 15, 22, 40, 52, 432, DateTimeKind.Unspecified).AddTicks(3052),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        },
                        new
                        {
                            Id = "70004fb2-e7f9-49a3-a4e1-19188d3b5c17",
                            CreatedAt = new DateTime(2023, 7, 25, 19, 47, 54, 970, DateTimeKind.Unspecified).AddTicks(3849),
                            CreatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef",
                            Description = "Aliquid ipsum esse inventore quas. Tempora voluptate et dolore ullam quidem voluptatem dolorum. Iure amet aut aut nulla quia eius aut a.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Veniam et ullam ut aut. Voluptas magnam vero. Dolorem eligendi o\"},{\"role\":\"assistant\",\"content\":\"Est et et. Quia aut qui similique numquam cumque laborum cupidit\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Nostrum consequatur adipisci impedit odio maiores qui et ut placeat. Odit fugit ipsum. Sint occaecati quo aut.",
                            ProjectId = "85d978b2-2dbb-4fe0-adf9-d0d5657d868a",
                            Tokens = 10134,
                            UpdatedAt = new DateTime(2023, 7, 25, 19, 47, 54, 970, DateTimeKind.Unspecified).AddTicks(3849),
                            UpdatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef"
                        },
                        new
                        {
                            Id = "e88a2181-894c-4005-898b-268298607d8a",
                            CreatedAt = new DateTime(2022, 8, 19, 23, 33, 31, 107, DateTimeKind.Unspecified).AddTicks(3145),
                            CreatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088",
                            Description = "Est quas qui voluptas cum. Et delectus ut laboriosam est. Quis impedit qui qui. Et aut laboriosam libero provident accusamus qui. Quasi ut aut totam ut laboriosam quo. Ad dolorem quisquam aliquam non corrupti incidunt.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Explicabo sapiente vitae est qui atque soluta quis error non. Au\"},{\"role\":\"user\",\"content\":\"Beatae et est reprehenderit et ducimus quam consequatur. Volupta\"},{\"role\":\"assistant\",\"content\":\"Dolorem officiis ut officia eos dolor nihil voluptas facere dign\"},{\"role\":\"system\",\"content\":\"Ex modi odio velit dolor voluptatem temporibus itaque aut ea. De\"},{\"role\":\"system\",\"content\":\"Dolorem error rerum et. Atque rerum magnam quia iusto consequunt\"},{\"role\":\"user\",\"content\":\"Odio iusto cum saepe dignissimos. Officia occaecati nihil ipsa m\"}]",
                            Model = "gpt-4",
                            Name = "Aut qui ut. Similique voluptatum dolorem possimus quos suscipit omnis provident. Voluptatibus qui numquam sit et alias dolorem e",
                            ProjectId = "02490e24-e61f-40d0-b1ce-f604d5435c87",
                            Tokens = 7536,
                            UpdatedAt = new DateTime(2022, 8, 19, 23, 33, 31, 107, DateTimeKind.Unspecified).AddTicks(3145),
                            UpdatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088"
                        },
                        new
                        {
                            Id = "d57fb6e0-0cfa-4e5b-9503-7c2837632ca6",
                            CreatedAt = new DateTime(2022, 9, 24, 15, 37, 29, 853, DateTimeKind.Unspecified).AddTicks(1988),
                            CreatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2",
                            Description = "Tempora praesentium magnam repudiandae quis. Autem laborum voluptas et ut dolor sed alias qui ab. Sint ad consequatur. Nihil excepturi et illo. Omnis fugit dolor mollitia dolor ea et dolor sit maiores.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"system\",\"content\":\"Et cum fuga distinctio. Fugiat cumque esse consequatur reprehend\"},{\"role\":\"assistant\",\"content\":\"Et ducimus eveniet provident. Neque voluptatibus excepturi iure\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Voluptates similique adipisci sunt fugiat ad nihil sed nam. Aut et autem veniam alias adipisci enim fugit. Quo ea incidunt provi",
                            ProjectId = "d46499b9-1bdd-4c01-98be-9d9bbd560d68",
                            Tokens = 1933,
                            UpdatedAt = new DateTime(2022, 9, 24, 15, 37, 29, 853, DateTimeKind.Unspecified).AddTicks(1988),
                            UpdatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2"
                        },
                        new
                        {
                            Id = "d77bf5f2-4d0f-41b8-bb89-92e7a0d6a4ce",
                            CreatedAt = new DateTime(2023, 4, 14, 8, 44, 12, 385, DateTimeKind.Unspecified).AddTicks(448),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Molestiae veniam explicabo quasi vel suscipit. Aut neque ut. Quia aut et dolore exercitationem quas repudiandae. Officiis quas quidem. Libero qui dolor et distinctio sed minus velit consequuntur occaecati.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Aut harum eum aut doloribus. Exercitationem accusantium minus re\"},{\"role\":\"assistant\",\"content\":\"Nam vitae voluptatem quidem tenetur illo eos omnis dolorem aut.\"},{\"role\":\"assistant\",\"content\":\"Autem veritatis quod. Ea architecto facere officiis accusantium.\"},{\"role\":\"system\",\"content\":\"Nesciunt omnis impedit magnam corrupti facilis est velit volupta\"},{\"role\":\"assistant\",\"content\":\"Aspernatur ad et reiciendis sit. Corrupti et officia dolor commo\"},{\"role\":\"user\",\"content\":\"Dolores quasi sed magnam omnis. Molestiae animi iure. Aut velit\"}]",
                            Model = "gpt-4",
                            Name = "A animi maiores. Consequatur dicta recusandae labore voluptatem et est. Magni aliquid alias unde recusandae sit sunt soluta omni",
                            ProjectId = "771c3266-ab4d-411b-b2ed-35a6eeb01e83",
                            Tokens = 706,
                            UpdatedAt = new DateTime(2023, 4, 14, 8, 44, 12, 385, DateTimeKind.Unspecified).AddTicks(448),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "23aafa22-24bc-4634-9a84-e1595c5b3875",
                            CreatedAt = new DateTime(2023, 6, 1, 11, 2, 15, 944, DateTimeKind.Unspecified).AddTicks(566),
                            CreatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12",
                            Description = "Quod et modi iure libero veniam enim recusandae vero. Esse facilis reiciendis aperiam atque dolor qui nobis dolores. Ut rerum beatae repellat.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Perspiciatis blanditiis placeat. Ad vitae quis id. Quisquam aliq\"},{\"role\":\"user\",\"content\":\"Corporis vitae iure rerum molestiae consequatur voluptatem dolor\"},{\"role\":\"system\",\"content\":\"Dolor eum eius inventore molestiae. Voluptas dignissimos sunt vi\"},{\"role\":\"system\",\"content\":\"Dolor non aperiam sint voluptatum. Odit reiciendis temporibus. A\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Officiis dolorem porro. Consequatur velit laborum ad cupiditate quisquam. Ut quo non ea fugit corrupti nam fugiat voluptate. Vel",
                            ProjectId = "9ee31024-e1e8-499e-89cb-1676e9872e32",
                            Tokens = 8378,
                            UpdatedAt = new DateTime(2023, 6, 1, 11, 2, 15, 944, DateTimeKind.Unspecified).AddTicks(566),
                            UpdatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12"
                        },
                        new
                        {
                            Id = "d0f36e99-d06a-4aa1-a1b2-5b2d1645178a",
                            CreatedAt = new DateTime(2022, 8, 26, 11, 3, 19, 652, DateTimeKind.Unspecified).AddTicks(2007),
                            CreatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9",
                            Description = "Ea suscipit harum qui earum quae hic et ea. Excepturi sunt consequatur consectetur magni. Qui occaecati nihil ut molestias beatae.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"A neque illum tenetur quisquam et id. Magnam facilis ut veritati\"},{\"role\":\"system\",\"content\":\"Sed aliquid et eius. Consectetur corporis quis maxime soluta. Pr\"},{\"role\":\"user\",\"content\":\"Placeat quisquam laudantium voluptatem et. Iure nemo harum dolor\"},{\"role\":\"system\",\"content\":\"Non voluptatem corrupti eos quasi qui rerum. Velit voluptatem to\"},{\"role\":\"system\",\"content\":\"Quibusdam ut cum qui occaecati. Est quae quod beatae. Autem saep\"},{\"role\":\"user\",\"content\":\"Molestias ut illum ut quia unde excepturi id. Ipsa eaque minus n\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Sed aut ut repellat est dicta. Dolores in repellat autem culpa similique ullam. Architecto quod quae omnis libero molestiae alia",
                            ProjectId = "f5f16745-8600-4a22-b864-4d86f1262478",
                            Tokens = 15082,
                            UpdatedAt = new DateTime(2022, 8, 26, 11, 3, 19, 652, DateTimeKind.Unspecified).AddTicks(2007),
                            UpdatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9"
                        },
                        new
                        {
                            Id = "de5003e5-fbf9-4782-9c52-6fd7b56c8523",
                            CreatedAt = new DateTime(2022, 9, 7, 11, 0, 31, 538, DateTimeKind.Unspecified).AddTicks(9306),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Consequuntur ut iure adipisci. Ipsam at qui accusantium amet assumenda. Fugiat quis dolore hic ab aut assumenda debitis. Inventore iste veritatis optio quis vel cumque doloremque modi.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Temporibus tenetur quae facilis perferendis. Unde nostrum accusa\"},{\"role\":\"user\",\"content\":\"Est dolorum eaque. Quis cupiditate dolorum aliquam dignissimos.\"},{\"role\":\"user\",\"content\":\"Voluptatem molestias consequatur. Modi impedit alias doloribus u\"},{\"role\":\"system\",\"content\":\"Delectus impedit quis repudiandae. Quam minima deserunt aut. Eve\"},{\"role\":\"user\",\"content\":\"Et dolorem minus quibusdam corrupti blanditiis et sit. Sit asper\"},{\"role\":\"assistant\",\"content\":\"Ullam vel in praesentium excepturi itaque reiciendis quo volupta\"},{\"role\":\"system\",\"content\":\"Tenetur quo ipsa praesentium ut iusto sit soluta. Et ut molestia\"},{\"role\":\"user\",\"content\":\"Eligendi rem quia eligendi possimus in quia ipsam. Laborum sunt\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Minima id culpa cumque necessitatibus eum omnis omnis aut. Consequatur sequi ut molestiae debitis voluptatem. Ipsam cupiditate r",
                            ProjectId = "2a3eec74-b118-41fc-99aa-f7a8b0b6b62c",
                            Tokens = 5853,
                            UpdatedAt = new DateTime(2022, 9, 7, 11, 0, 31, 538, DateTimeKind.Unspecified).AddTicks(9306),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        },
                        new
                        {
                            Id = "41389ae7-21ff-490e-a7dc-234ca62ad1d5",
                            CreatedAt = new DateTime(2023, 11, 20, 23, 59, 18, 216, DateTimeKind.Unspecified).AddTicks(2413),
                            CreatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd",
                            Description = "Tenetur perferendis sit est dolorem exercitationem molestiae. Et temporibus molestias quaerat sit. Dolorum quis consectetur in nostrum. Perferendis et incidunt minima facere. Eum repellat rerum provident.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Ut eius rem aut laudantium. Commodi accusantium nobis nihil quam\"}]",
                            Model = "gpt-4",
                            Name = "Non molestiae voluptas voluptates vel. Fugiat aut nihil debitis deserunt dolor est esse. Tempore eos aliquid placeat autem.",
                            ProjectId = "f75b9f22-1cf4-4c0d-a838-05525371fa44",
                            Tokens = 9527,
                            UpdatedAt = new DateTime(2023, 11, 20, 23, 59, 18, 216, DateTimeKind.Unspecified).AddTicks(2413),
                            UpdatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd"
                        },
                        new
                        {
                            Id = "043fe92e-b719-4f28-8074-d3a48c9deb70",
                            CreatedAt = new DateTime(2022, 5, 13, 14, 8, 5, 63, DateTimeKind.Unspecified).AddTicks(8696),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Dolores est assumenda eos impedit omnis animi. Et nihil enim non. Odio ullam facilis. Vero est et. Est omnis perferendis.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"system\",\"content\":\"Distinctio id non sed sed amet. Est eum ipsa voluptas qui quod i\"},{\"role\":\"user\",\"content\":\"Quas dolorem est eum excepturi tempora qui. Voluptatem libero od\"},{\"role\":\"system\",\"content\":\"A fuga fugit aut. Quis enim sit ut ratione. Aspernatur impedit v\"},{\"role\":\"user\",\"content\":\"Nemo dolorum dignissimos rem. Maxime nobis aut voluptatem enim a\"},{\"role\":\"system\",\"content\":\"Explicabo est magnam eveniet. Unde quia totam velit minima. Quia\"},{\"role\":\"user\",\"content\":\"Aliquid ut voluptatem. Necessitatibus laboriosam corrupti. Animi\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Ut voluptates est velit natus repudiandae. Et et sit. Dignissimos molestias magnam et id quibusdam et ex et. Id amet vitae.",
                            ProjectId = "480b8043-b15d-4124-b5dc-e93e7717cf8f",
                            Tokens = 9480,
                            UpdatedAt = new DateTime(2022, 5, 13, 14, 8, 5, 63, DateTimeKind.Unspecified).AddTicks(8696),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "0e0ed653-4588-40ac-a4b2-2e06eb2d0ec4",
                            CreatedAt = new DateTime(2023, 12, 24, 13, 12, 10, 867, DateTimeKind.Unspecified).AddTicks(942),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Blanditiis ullam laborum in amet ut minima dolorum. Ut alias pariatur rerum molestiae voluptas ducimus veniam modi non. Expedita qui porro voluptatem nihil.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Ea animi non excepturi consequuntur iure quia provident. Sequi f\"},{\"role\":\"user\",\"content\":\"Vel enim accusamus. Cumque eius temporibus. Excepturi earum veli\"},{\"role\":\"user\",\"content\":\"Quidem consectetur repellat reprehenderit nisi quo cupiditate. F\"},{\"role\":\"user\",\"content\":\"Repellendus ex cum tenetur odio provident voluptatem. Tenetur es\"},{\"role\":\"assistant\",\"content\":\"Tempora totam magni aut fugit nesciunt consequatur alias eos. Es\"},{\"role\":\"user\",\"content\":\"Nam qui commodi est porro facilis deleniti blanditiis et. Porro\"},{\"role\":\"system\",\"content\":\"Corporis quibusdam eaque eius et aliquid dignissimos. Quia dolor\"},{\"role\":\"system\",\"content\":\"Architecto in qui non ratione sit nobis accusamus dicta quisquam\"},{\"role\":\"system\",\"content\":\"Explicabo cupiditate aut ut quos. Et et ut vel voluptatibus elig\"}]",
                            Model = "gpt-4",
                            Name = "Et ipsam voluptatem minima et omnis. Velit magni est sit non quia voluptatem. Voluptate et eveniet autem velit. Fugiat ducimus a",
                            ProjectId = "c3151aa7-60b9-4682-a800-98077c6cef31",
                            Tokens = 6439,
                            UpdatedAt = new DateTime(2023, 12, 24, 13, 12, 10, 867, DateTimeKind.Unspecified).AddTicks(942),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        },
                        new
                        {
                            Id = "c5115b51-cbdf-4b18-b9b0-a2a2b618ab04",
                            CreatedAt = new DateTime(2022, 6, 1, 8, 49, 10, 482, DateTimeKind.Unspecified).AddTicks(4530),
                            CreatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef",
                            Description = "Voluptatem voluptas molestias quia. Quo dolor voluptatem est excepturi suscipit necessitatibus incidunt quibusdam tenetur. Ea ea vero quaerat dolore aliquam consequatur. Dolorum ut quia suscipit.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"system\",\"content\":\"Culpa earum rerum aliquid corporis et. Ea et magni et. Animi nat\"},{\"role\":\"user\",\"content\":\"Quo suscipit rem cum autem hic autem saepe quidem iure. Tenetur\"},{\"role\":\"assistant\",\"content\":\"Rerum veniam laudantium corporis. Consectetur ipsa aut voluptate\"},{\"role\":\"assistant\",\"content\":\"Occaecati quis temporibus aut voluptatibus non consequuntur porr\"},{\"role\":\"user\",\"content\":\"Officia excepturi nihil enim hic ducimus commodi nihil. Delectus\"},{\"role\":\"assistant\",\"content\":\"Minima ratione mollitia doloremque ducimus dolores consequuntur\"},{\"role\":\"assistant\",\"content\":\"Et voluptatibus sequi enim qui sequi debitis ut cum. Optio repre\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Molestiae rerum ipsam. Esse quos explicabo. Iure assumenda repudiandae vel qui deleniti occaecati nemo eum blanditiis. Debitis i",
                            ProjectId = "85d978b2-2dbb-4fe0-adf9-d0d5657d868a",
                            Tokens = 6724,
                            UpdatedAt = new DateTime(2022, 6, 1, 8, 49, 10, 482, DateTimeKind.Unspecified).AddTicks(4530),
                            UpdatedById = "dd767247-16e5-41c9-a0d2-d5f9883146ef"
                        },
                        new
                        {
                            Id = "6f653840-a482-49c7-a670-ec0080e1da7b",
                            CreatedAt = new DateTime(2022, 3, 4, 4, 23, 37, 760, DateTimeKind.Unspecified).AddTicks(487),
                            CreatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088",
                            Description = "Tenetur vel sit omnis consequatur sed et rerum inventore minus. Qui sunt ab et animi. Ab quia voluptatem sit explicabo molestias quia. Odit qui dolore. Dicta sed fugit culpa. Officia aperiam sapiente fugit id porro et.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Velit doloribus nam quaerat dolorem nihil et. Quae aut in alias\"},{\"role\":\"system\",\"content\":\"Nulla aut velit non. Accusamus ea neque sunt culpa qui est labor\"},{\"role\":\"assistant\",\"content\":\"Atque et numquam ad qui nemo. Blanditiis est cupiditate rem quis\"},{\"role\":\"system\",\"content\":\"Veniam aliquid illo repellat ad occaecati qui. Error neque eos m\"},{\"role\":\"assistant\",\"content\":\"Nam quis velit nam iste dolorem recusandae facilis. Deserunt vel\"},{\"role\":\"user\",\"content\":\"Id similique consequatur autem ea quam. Sed officiis accusamus a\"},{\"role\":\"system\",\"content\":\"Nihil corporis dolorum perferendis. Dolorem odio ab tempore et q\"}]",
                            Model = "gpt-4",
                            Name = "Nostrum cupiditate sed totam qui. Quo minima quod repellendus sint nesciunt temporibus. Distinctio ad ut repudiandae.",
                            ProjectId = "02490e24-e61f-40d0-b1ce-f604d5435c87",
                            Tokens = 13720,
                            UpdatedAt = new DateTime(2022, 3, 4, 4, 23, 37, 760, DateTimeKind.Unspecified).AddTicks(487),
                            UpdatedById = "13ee4105-45c5-4c2c-8ebe-0da1d7604088"
                        },
                        new
                        {
                            Id = "e769e6b0-c2ed-487a-8fcc-234e9790705b",
                            CreatedAt = new DateTime(2023, 12, 17, 6, 23, 25, 92, DateTimeKind.Unspecified).AddTicks(2232),
                            CreatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2",
                            Description = "Aut sapiente id porro et molestiae. Et dolorem minima in voluptate eius fugit sit debitis. Praesentium ab cupiditate sed est sequi et provident atque.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Autem veniam nostrum explicabo sit rem similique ea. Quo vero nu\"},{\"role\":\"system\",\"content\":\"Itaque quasi unde earum natus libero. Soluta corporis ratione ip\"},{\"role\":\"assistant\",\"content\":\"Culpa nihil perferendis. Et id et. At animi aperiam sapiente. Re\"},{\"role\":\"user\",\"content\":\"Quasi molestiae nihil recusandae voluptatem nihil non dolorem no\"},{\"role\":\"user\",\"content\":\"Asperiores officiis tempore sequi velit quo non. Blanditiis qui\"},{\"role\":\"assistant\",\"content\":\"Consequatur quia eaque nemo et id nemo dicta. Ea nisi autem qui\"},{\"role\":\"system\",\"content\":\"Et dicta voluptate molestias cupiditate et voluptatem. Omnis dol\"}]",
                            Model = "gpt-4",
                            Name = "Aut dolor non sed voluptatem praesentium praesentium expedita. Sunt aspernatur veritatis. Sit saepe quidem et dolores excepturi",
                            ProjectId = "d46499b9-1bdd-4c01-98be-9d9bbd560d68",
                            Tokens = 8325,
                            UpdatedAt = new DateTime(2023, 12, 17, 6, 23, 25, 92, DateTimeKind.Unspecified).AddTicks(2232),
                            UpdatedById = "9aef1613-965e-4579-9b03-95c05a90b0e2"
                        },
                        new
                        {
                            Id = "1efb87fa-3f05-41fe-a2ca-0ff55352635b",
                            CreatedAt = new DateTime(2022, 10, 6, 1, 23, 14, 665, DateTimeKind.Unspecified).AddTicks(3941),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Animi reprehenderit sint modi est sed ad culpa similique. Harum fugiat cum optio quas provident dolore. Tempore occaecati qui modi nulla. Aut et quis ut.",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"user\",\"content\":\"Corporis illum id pariatur ea qui quia dolore. Facilis non labor\"},{\"role\":\"system\",\"content\":\"Occaecati omnis neque provident non aut amet id sint. Natus et e\"},{\"role\":\"system\",\"content\":\"Sit rerum aut ipsam adipisci quia incidunt dolore voluptatem et.\"},{\"role\":\"user\",\"content\":\"Qui et omnis ut. Quidem excepturi eos consequatur accusantium ei\"},{\"role\":\"assistant\",\"content\":\"Sequi nostrum tempora eaque quas dolor quidem enim eius. Accusam\"},{\"role\":\"system\",\"content\":\"Non ut et quaerat nihil voluptatem. Facilis iste ut qui quas et\"},{\"role\":\"assistant\",\"content\":\"Vitae tempore placeat et dolorem sed. Numquam fugit ex incidunt\"},{\"role\":\"system\",\"content\":\"Temporibus sit sit quos eos. Ea autem et qui minima omnis et mol\"},{\"role\":\"assistant\",\"content\":\"Iusto fugiat quae est sit ut hic fugit natus neque. Hic ea sit.\"},{\"role\":\"assistant\",\"content\":\"Inventore inventore autem repudiandae aut quisquam quia voluptas\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Debitis cumque nobis distinctio dolores delectus quo quidem voluptatibus. Ipsa qui molestiae blanditiis ea voluptatem consequatu",
                            ProjectId = "771c3266-ab4d-411b-b2ed-35a6eeb01e83",
                            Tokens = 12284,
                            UpdatedAt = new DateTime(2022, 10, 6, 1, 23, 14, 665, DateTimeKind.Unspecified).AddTicks(3941),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "6e7a4f5f-c3de-442c-aa22-3685b91b2144",
                            CreatedAt = new DateTime(2022, 8, 15, 6, 18, 32, 980, DateTimeKind.Unspecified).AddTicks(2995),
                            CreatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12",
                            Description = "Aut hic ipsum distinctio hic. Aliquam quos eaque animi quae autem. Sequi aut dolorum. Omnis voluptatibus in eveniet enim.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Quam provident qui aut voluptate quae animi est. Eveniet aut qua\"},{\"role\":\"assistant\",\"content\":\"Corrupti minima nam quibusdam cupiditate alias neque fugit. Sed\"}]",
                            Model = "gpt-4",
                            Name = "Aliquam repellendus aut fugit asperiores blanditiis aliquam voluptatem. Qui ea est distinctio perferendis. Vitae et numquam exce",
                            ProjectId = "9ee31024-e1e8-499e-89cb-1676e9872e32",
                            Tokens = 2092,
                            UpdatedAt = new DateTime(2022, 8, 15, 6, 18, 32, 980, DateTimeKind.Unspecified).AddTicks(2995),
                            UpdatedById = "f524888c-56f3-4d04-be92-fe6b4f895b12"
                        },
                        new
                        {
                            Id = "70732666-cb16-481b-a676-77caae32bbfb",
                            CreatedAt = new DateTime(2022, 3, 13, 21, 20, 39, 511, DateTimeKind.Unspecified).AddTicks(5118),
                            CreatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9",
                            Description = "Molestias quis laboriosam mollitia enim dignissimos autem sed. At dolorem rerum non laudantium molestias ab qui eveniet. Ad ut hic nostrum vero quia rerum eaque aliquam. Saepe dignissimos quia aspernatur molestias nihil. Voluptate quam atque et asperiores",
                            IsDeleted = false,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Eos non nihil dolor aut. In dignissimos consequatur quia quia te\"},{\"role\":\"assistant\",\"content\":\"Quos hic dolorum sit est id placeat suscipit ea eligendi. Volupt\"},{\"role\":\"assistant\",\"content\":\"Totam amet repellendus dignissimos qui recusandae et sed non del\"},{\"role\":\"system\",\"content\":\"Incidunt dicta vero. Ducimus est autem possimus facere sit quo c\"},{\"role\":\"system\",\"content\":\"Iure quod error molestias. Ullam minus officiis eum voluptatum c\"},{\"role\":\"user\",\"content\":\"Ut veritatis placeat mollitia distinctio mollitia nihil neque. D\"},{\"role\":\"assistant\",\"content\":\"Quae aut blanditiis sapiente. Quia voluptatem quidem maxime eum\"},{\"role\":\"system\",\"content\":\"Qui rerum quasi quis vel unde sed. Esse doloribus qui est dolore\"},{\"role\":\"assistant\",\"content\":\"Asperiores numquam nobis alias. Officia perferendis dolor quis a\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Aliquam laborum consequuntur voluptatem numquam et numquam corrupti necessitatibus. Doloribus quo qui corporis distinctio volupt",
                            ProjectId = "f5f16745-8600-4a22-b864-4d86f1262478",
                            Tokens = 757,
                            UpdatedAt = new DateTime(2022, 3, 13, 21, 20, 39, 511, DateTimeKind.Unspecified).AddTicks(5118),
                            UpdatedById = "e79ba770-a43f-4069-b95f-ad60a62320c9"
                        },
                        new
                        {
                            Id = "c18feec0-a694-4658-9d03-926c36f6d5da",
                            CreatedAt = new DateTime(2023, 10, 24, 8, 47, 9, 719, DateTimeKind.Unspecified).AddTicks(2312),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Qui consequatur odit et est voluptatem autem vitae. Aut voluptas fugiat illo beatae repudiandae autem error est. Nihil minima soluta impedit animi molestiae sunt corrupti. Quaerat nihil aut voluptatem praesentium rerum enim. Et ut eos qui corporis quisquam",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"assistant\",\"content\":\"Illum harum placeat quidem dolor aliquam explicabo error volupta\"},{\"role\":\"system\",\"content\":\"Dolor laudantium labore quis voluptas ut eum veniam. Praesentium\"},{\"role\":\"assistant\",\"content\":\"Nam officiis quas. Nemo dolor natus et iste repellendus molestia\"},{\"role\":\"user\",\"content\":\"Quam rerum voluptas error. Iure qui doloremque explicabo ducimus\"},{\"role\":\"user\",\"content\":\"Placeat fuga temporibus quis et alias harum voluptatem. Officiis\"},{\"role\":\"assistant\",\"content\":\"Ratione aperiam consequatur rerum voluptatibus veniam. Pariatur\"},{\"role\":\"system\",\"content\":\"Dolores deserunt tempore repudiandae fuga. Praesentium quos in q\"},{\"role\":\"user\",\"content\":\"Cupiditate sint adipisci earum. Numquam consequatur molestiae et\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Et quasi reprehenderit dolor deserunt modi excepturi voluptas. Illum at tenetur aperiam est. Natus qui possimus. Tenetur neque e",
                            ProjectId = "2a3eec74-b118-41fc-99aa-f7a8b0b6b62c",
                            Tokens = 10927,
                            UpdatedAt = new DateTime(2023, 10, 24, 8, 47, 9, 719, DateTimeKind.Unspecified).AddTicks(2312),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        },
                        new
                        {
                            Id = "0068240d-7419-40ac-b3e5-8e68378d8aae",
                            CreatedAt = new DateTime(2022, 4, 20, 8, 30, 21, 959, DateTimeKind.Unspecified).AddTicks(1498),
                            CreatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd",
                            Description = "Natus vero fugiat quia incidunt. Fuga aut aut. Voluptatum enim exercitationem labore libero alias quia est magnam.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"system\",\"content\":\"Rerum nisi qui porro. Qui vitae vel qui sapiente libero ut nihil\"},{\"role\":\"user\",\"content\":\"Animi voluptas eum et quis qui ipsam temporibus. Incidunt velit\"},{\"role\":\"assistant\",\"content\":\"Corporis molestiae perferendis enim optio qui quo. Rerum dolores\"},{\"role\":\"user\",\"content\":\"Facilis quae cupiditate quis et dolore sed libero corporis omnis\"},{\"role\":\"system\",\"content\":\"Harum nobis doloremque eum rerum molestias illo ut. Deserunt ali\"},{\"role\":\"user\",\"content\":\"Est quia quod libero aperiam quia sapiente dolores. Doloremque f\"},{\"role\":\"assistant\",\"content\":\"Aut voluptas dolore ad at recusandae quidem. Eos unde repellendu\"},{\"role\":\"user\",\"content\":\"Rerum voluptatem nam eum. Voluptas ad aliquid culpa ut dignissim\"}]",
                            Model = "gpt-3.5-trubo",
                            Name = "Sit sit quaerat quia ullam cumque soluta. Cupiditate praesentium perspiciatis eaque molestiae consequuntur ut neque. Quisquam pl",
                            ProjectId = "f75b9f22-1cf4-4c0d-a838-05525371fa44",
                            Tokens = 13655,
                            UpdatedAt = new DateTime(2022, 4, 20, 8, 30, 21, 959, DateTimeKind.Unspecified).AddTicks(1498),
                            UpdatedById = "4a74c5b1-24bb-4fac-bd3e-6b7947f3f1dd"
                        },
                        new
                        {
                            Id = "2a03b6db-b6d2-4575-b074-382694dc0724",
                            CreatedAt = new DateTime(2023, 2, 25, 3, 45, 23, 587, DateTimeKind.Unspecified).AddTicks(5121),
                            CreatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87",
                            Description = "Deserunt commodi impedit quam aut aperiam ex. Accusantium facere aliquid distinctio consequatur cupiditate et natus quas. Dolorem ut facere recusandae quam impedit ea omnis.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"At hic fugit doloribus numquam earum distinctio magnam dolor dol\"},{\"role\":\"system\",\"content\":\"Temporibus dolor quibusdam. Consequatur at tempore mollitia quo\"},{\"role\":\"system\",\"content\":\"Illum voluptates facere magni distinctio rerum quibusdam aliquid\"},{\"role\":\"assistant\",\"content\":\"Modi eos nostrum nisi quasi beatae dolorem saepe. Facere et inci\"},{\"role\":\"system\",\"content\":\"Recusandae suscipit sed et iste sed provident. Et et quos fugiat\"},{\"role\":\"user\",\"content\":\"Vel libero inventore esse atque. Sed unde voluptatem amet provid\"}]",
                            Model = "gpt-4",
                            Name = "Ea necessitatibus assumenda eaque hic est aut. Tempora incidunt atque ipsam nisi non. Et iure numquam.",
                            ProjectId = "480b8043-b15d-4124-b5dc-e93e7717cf8f",
                            Tokens = 7086,
                            UpdatedAt = new DateTime(2023, 2, 25, 3, 45, 23, 587, DateTimeKind.Unspecified).AddTicks(5121),
                            UpdatedById = "2bad0a52-f80d-4780-94a0-2909bc4a7a87"
                        },
                        new
                        {
                            Id = "a9073efe-4f16-48d5-a22d-682f03cfa72b",
                            CreatedAt = new DateTime(2022, 5, 16, 11, 17, 17, 471, DateTimeKind.Unspecified).AddTicks(7637),
                            CreatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555",
                            Description = "Adipisci quaerat asperiores asperiores. Dicta ut nihil. Vitae occaecati maxime dolorem eum ea. Possimus corrupti eos cumque exercitationem. Libero dolorem alias ipsum eius quis quasi eaque.",
                            IsDeleted = true,
                            Messages = "[{\"role\":\"user\",\"content\":\"Consequatur voluptatem animi ullam dolores autem et aperiam non.\"},{\"role\":\"user\",\"content\":\"Eum corporis eveniet quaerat possimus sapiente. Voluptatem est a\"},{\"role\":\"system\",\"content\":\"Quis eaque blanditiis veritatis. Nihil inventore et sunt. Vero e\"},{\"role\":\"assistant\",\"content\":\"Dolorum veritatis voluptas quia aperiam quis mollitia eaque mole\"},{\"role\":\"system\",\"content\":\"Nesciunt quam et ut consequuntur ullam harum. Velit aliquid et n\"},{\"role\":\"system\",\"content\":\"Labore nisi possimus. Est laborum sunt quis sunt dicta assumenda\"},{\"role\":\"assistant\",\"content\":\"Et nesciunt ratione eum. Ipsa maiores iusto corrupti quod repell\"}]",
                            Model = "gpt-4",
                            Name = "Consectetur deserunt qui et tempora est sit. Quo quibusdam autem quis. Mollitia aliquam sed nobis ut quia. Dicta iste dicta vita",
                            ProjectId = "c3151aa7-60b9-4682-a800-98077c6cef31",
                            Tokens = 6098,
                            UpdatedAt = new DateTime(2022, 5, 16, 11, 17, 17, 471, DateTimeKind.Unspecified).AddTicks(7637),
                            UpdatedById = "aa52b4b1-5d82-4f6d-ac2d-033c8202c555"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Project", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Prompt", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptHub2.Server.Models.Project", "Project")
                        .WithMany("Prompts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PromptHub2.Server.Models.Project", b =>
                {
                    b.Navigation("Prompts");
                });
#pragma warning restore 612, 618
        }
    }
}
